/*
    Copyright or (c) or Copr. Project-Team S3 (Sound Signals and Systems) and
    Analysis/Synthesis team, Laboratory of Sciences and Technologies of Music and
    Sound (UMR 9912), IRCAM-CNRS-UPMC, 1 place Igor Stravinsky, F-75004 Paris
    * contributors : Antoine Falaize, Thomas Helie,
    * corresponding contributor: antoine.falaize@ircam.fr
    * date: 2016/12/31 12:47:34

    This has been geerated by PyPHS which purpose is to generate C++
    code for the simulation of multiphysics system described by graph structures.

    This software is governed by the CeCILL-B license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-B
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights, and the successive licensors  have only  limited liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-B license and that you accept its terms.

    Created on 2016/12/31 12:47:34

    author: Antoine Falaize


===========================================================================

    This file was automatically generated by PyPHS, date 2017/01/30 20:13:22.

    It contains the code for the simulation of system 'PHSCORE'.

===========================================================================
*/


#ifndef PHSCORE_H
#define PHSCORE_H

#include "iostream"
#include "vector"
#include "math.h"

# include "data.h"

#include <This Should be your local path to the eigen library (it can be \
configured in the script "config.py" from your local pyphs installation)./Eigen/Dense>

using namespace std;
using namespace Eigen;

class PHSCORE {

// PUBLIC    
    public:
    void update(vector<double> &, vector<double> &);
    
    // Acessors to Arguments, return vector<double>
    
    vector<double> x_vector() const;
    vector<double> xl_vector() const;
    vector<double> dx_vector() const;
    vector<double> w_vector() const;
    vector<double> u_vector() const;
    vector<double> p_vector() const;
    vector<double> vl_vector() const;
    vector<double> vnl_vector() const;
    
    // Acessors to Arguments, return Matrix<double, n, m>
    
    Matrix<double, 2, 1> x() const;
    Matrix<double, 0, 1> xl() const;
    Matrix<double, 2, 1> dx() const;
    Matrix<double, 3, 1> w() const;
    Matrix<double, 1, 1> u() const;
    Matrix<double, 0, 1> p() const;
    Matrix<double, 0, 1> vl() const;
    Matrix<double, 5, 1> vnl() const;
    
    // Mutators for Arguments, type = vector<double>
    
    void set_x(vector<double> &);
    void set_xl(vector<double> &);
    void set_dx(vector<double> &);
    void set_w(vector<double> &);
    void set_u(vector<double> &);
    void set_p(vector<double> &);
    void set_vl(vector<double> &);
    void set_vnl(vector<double> &);
    
    // Mutators for Arguments, type = Matrix<double, n, m>
    
    void set_x(Matrix<double, 2, 1> &);
    void set_xl(Matrix<double, 0, 1> &);
    void set_dx(Matrix<double, 2, 1> &);
    void set_w(Matrix<double, 3, 1> &);
    void set_u(Matrix<double, 1, 1> &);
    void set_p(Matrix<double, 0, 1> &);
    void set_vl(Matrix<double, 0, 1> &);
    void set_vnl(Matrix<double, 5, 1> &);
    
    // Functions Results Accessors
    
    Matrix<double, 2, 1> dxH() const;
    Matrix<double, 3, 1> z() const;
    Matrix<double, 1, 1> y() const;
    Matrix<double, 5, 1> fnl() const;
    Matrix<double, 5, 5> jac_fnl() const;
    Matrix<double, 5, 5> Inl() const;
    Matrix<double, 0, 0> iDl() const;
    Matrix<double, 0, 0> barNlxl() const;
    Matrix<double, 0, 5> barNlnl() const;
    Matrix<double, 0, 1> barNly() const;
    Matrix<double, 5, 5> barNnlnl() const;
    Matrix<double, 5, 0> barNnll() const;
    Matrix<double, 5, 0> barNnlxl() const;
    Matrix<double, 5, 1> barNnly() const;
    
    // Functions Results Accessors
    
    vector<double> dxH_vector() const;
    vector<double> z_vector() const;
    vector<double> y_vector() const;
    vector<double> fnl_vector() const;
    vector<double> iDl_vector() const;
    vector<double> barNlxl_vector() const;
    vector<double> barNlnl_vector() const;
    vector<double> barNly_vector() const;
    
    // Oprations Results Accessors
    
    Matrix<double, 2, 1> ud_x() const;
    Matrix<double, 5, 5> Nnlnl() const;
    Matrix<double, 5, 1> Nnly() const;
    Matrix<double, 5, 1> c() const;
    Matrix<double, 5, 1> impfunc() const;
    Matrix<double, 5, 1> save_impfunc() const;
    Matrix<double, 5, 5> jac_impfunc() const;
    Matrix<double, 5, 5> ijac_impfunc() const;
    double res_impfunc() const;
    double step_impfunc() const;
    Matrix<double, 5, 1> ud_vnl() const;
    
    // Oprations Results Accessors
    
    vector<double> ud_x_vector() const;
    vector<double> c_vector() const;
    vector<double> impfunc_vector() const;
    vector<double> save_impfunc_vector() const;
    vector<double> ud_vnl_vector() const;
    
    // Default Constructor
    
    PHSCORE();
    
    // Constructor with vector state initalization
    
    PHSCORE(vector<double> &);
    
    // Constructor with matrix state initalization
    
    PHSCORE(Matrix<double, 2, 1> &);
    
    // Default Destructor
    
    ~PHSCORE();


// PRIVATE    
    private:
    
    // Parameters
    
    const unsigned int subs_ref = 0;
    
    const double * _fs = & subs[subs_ref][0];
    const double * C = & subs[subs_ref][1];
    const double * mu = & subs[subs_ref][2];
    const double * L = & subs[subs_ref][3];
    const double * v0 = & subs[subs_ref][4];
    const double * gmin = & subs[subs_ref][5];
    const double * Is = & subs[subs_ref][6];
    const double * Rd = & subs[subs_ref][7];
    
    // Arguments
    
    Matrix<double, 8, 1> args;
    
    double * xL = & args(0, 0);
    double * xC = & args(1, 0);
    double * dxL = & args(2, 0);
    double * dxC = & args(3, 0);
    double * wD = & args(4, 0);
    double * wD_R = & args(5, 0);
    double * wD_gmin = & args(6, 0);
    double * uin = & args(7, 0);
    
    // Functions Results Definitions
    
    Matrix<double, 2, 1> _dxH;
    Matrix<double, 3, 1> _z;
    Matrix<double, 1, 1> _y;
    Matrix<double, 5, 1> _fnl;
    Matrix<double, 5, 5> _jac_fnl;
    Matrix<double, 5, 5> _Inl;
    Matrix<double, 0, 0> _iDl;
    Matrix<double, 0, 0> _barNlxl;
    Matrix<double, 0, 5> _barNlnl;
    Matrix<double, 0, 1> _barNly;
    Matrix<double, 5, 5> _barNnlnl;
    Matrix<double, 5, 0> _barNnll;
    Matrix<double, 5, 0> _barNnlxl;
    Matrix<double, 5, 1> _barNnly;
    
    // Functions Results Updates
    
    void dxH_update();
    void z_update();
    void y_update();
    void fnl_update();
    void jac_fnl_update();
    void Inl_update();
    void iDl_update();
    void barNlxl_update();
    void barNlnl_update();
    void barNly_update();
    void barNnlnl_update();
    void barNnll_update();
    void barNnlxl_update();
    void barNnly_update();
    
    // Operations Results Definition
    
    Matrix<double, 2, 1> _ud_x;
    Matrix<double, 5, 5> _Nnlnl;
    Matrix<double, 5, 1> _Nnly;
    Matrix<double, 5, 1> _c;
    Matrix<double, 5, 1> _impfunc;
    Matrix<double, 5, 1> _save_impfunc;
    Matrix<double, 5, 5> _jac_impfunc;
    Matrix<double, 5, 5> _ijac_impfunc;
    double _res_impfunc;
    double _step_impfunc;
    Matrix<double, 5, 1> _ud_vnl;
    
    // Oprations Results Updates
    
    void ud_x_update();
    void Nnlnl_update();
    void Nnly_update();
    void c_update();
    void impfunc_update();
    void save_impfunc_update();
    void jac_impfunc_update();
    void ijac_impfunc_update();
    void res_impfunc_update();
    void step_impfunc_update();
    void ud_vnl_update();
    
    // Initialization
    
    void init();
};

#endif /* PHSCORE_H */
