/*
    Copyright or (c) or Copr. Project-Team S3 (Sound Signals and Systems) and
    Analysis/Synthesis team, Laboratory of Sciences and Technologies of Music and
    Sound (UMR 9912), IRCAM-CNRS-UPMC, 1 place Igor Stravinsky, F-75004 Paris
    * contributors : Antoine Falaize, Thomas Helie,
    * corresponding contributor: antoine.falaize@ircam.fr
    * date: 2016/12/31 12:47:34

    This has been geerated by PyPHS which purpose is to generate C++
    code for the simulation of multiphysics system described by graph structures.

    This software is governed by the CeCILL-B license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-B
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights, and the successive licensors  have only  limited liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-B license and that you accept its terms.

    Created on 2016/12/31 12:47:34

    author: Antoine Falaize


===========================================================================

    This file was automatically generated by PyPHS, date 2017/04/16 16:52:08.

    It contains the code for the simulation of system 'CORE'.

===========================================================================
*/

#include "core.h"

// PUBLIC    
    
    void CORE::update(vector<double> & u_vec, vector<double> & p_vec){
    
        set_u(u_vec);
        set_p(p_vec);
        
        ud_x_update();
        set_x(_ud_x);
        jacFll_update();
        jacFnll_update();
        ijacFll_update();
        Gl_update();
        Gnl_update();
        Fnl_update();
        res_Fnl_update();
        
        unsigned int iter_res_Fnl = 0;
        _step_Fnl = 1;
        while ((iter_res_Fnl<10) & (res_Fnl()>1e-16) & (step_Fnl()>1e-16)){    
            save_Fnl_update();
            jacGlnl_update();
            jacGnlnl_update();
            jacFnl_update();
            ijacFnl_update();
            ud_vnl_update();
            set_vnl(_ud_vnl);
            Gl_update();
            Gnl_update();
            Fnl_update();
            res_Fnl_update();
            step_Fnl_update();iter_res_Fnl += 1;
        }
        
        ud_vl_update();
        set_vl(_ud_vl);
        dxH_update();
        z_update();
        y_update();
    }
    
    // Acessors to Arguments, return vector<double>
    
    
    vector<double> CORE::x_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = *qfelt;    
        v[1] = *xbeamK4;    
        v[2] = *xbeamK3;    
        v[3] = *xbeamK2;    
        v[4] = *xbeamK1;    
        v[5] = *xbeamK0;    
        v[6] = *xbeamM0;    
        v[7] = *xbeamM1;    
        v[8] = *xbeamM2;    
        v[9] = *xbeamM3;    
        v[10] = *xbeamM4;    
        v[11] = *xmass;    
        return v;
    }
    
    vector<double> CORE::xl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> CORE::xnl_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = *qfelt;    
        v[1] = *xbeamK4;    
        v[2] = *xbeamK3;    
        v[3] = *xbeamK2;    
        v[4] = *xbeamK1;    
        v[5] = *xbeamK0;    
        v[6] = *xbeamM0;    
        v[7] = *xbeamM1;    
        v[8] = *xbeamM2;    
        v[9] = *xbeamM3;    
        v[10] = *xbeamM4;    
        v[11] = *xmass;    
        return v;
    }
    
    vector<double> CORE::dx_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = *dqfelt;    
        v[1] = *dxbeamK4;    
        v[2] = *dxbeamK3;    
        v[3] = *dxbeamK2;    
        v[4] = *dxbeamK1;    
        v[5] = *dxbeamK0;    
        v[6] = *dxbeamM0;    
        v[7] = *dxbeamM1;    
        v[8] = *dxbeamM2;    
        v[9] = *dxbeamM3;    
        v[10] = *dxbeamM4;    
        v[11] = *dxmass;    
        return v;
    }
    
    vector<double> CORE::dxl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> CORE::dxnl_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = *dqfelt;    
        v[1] = *dxbeamK4;    
        v[2] = *dxbeamK3;    
        v[3] = *dxbeamK2;    
        v[4] = *dxbeamK1;    
        v[5] = *dxbeamK0;    
        v[6] = *dxbeamM0;    
        v[7] = *dxbeamM1;    
        v[8] = *dxbeamM2;    
        v[9] = *dxbeamM3;    
        v[10] = *dxbeamM4;    
        v[11] = *dxmass;    
        return v;
    }
    
    vector<double> CORE::w_vector() const {    
        vector<double> v = vector<double>(6);    
        v[0] = *wbeamA4;    
        v[1] = *wbeamA3;    
        v[2] = *wbeamA2;    
        v[3] = *wbeamA1;    
        v[4] = *wbeamA0;    
        v[5] = *dtqfelt;    
        return v;
    }
    
    vector<double> CORE::wl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> CORE::wnl_vector() const {    
        vector<double> v = vector<double>(6);    
        v[0] = *wbeamA4;    
        v[1] = *wbeamA3;    
        v[2] = *wbeamA2;    
        v[3] = *wbeamA1;    
        v[4] = *wbeamA0;    
        v[5] = *dtqfelt;    
        return v;
    }
    
    vector<double> CORE::u_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = *uinput;    
        return v;
    }
    
    vector<double> CORE::p_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> CORE::v_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = *dqfelt;    
        v[1] = *dxbeamK4;    
        v[2] = *dxbeamK3;    
        v[3] = *dxbeamK2;    
        v[4] = *dxbeamK1;    
        v[5] = *dxbeamK0;    
        v[6] = *dxbeamM0;    
        v[7] = *dxbeamM1;    
        v[8] = *dxbeamM2;    
        v[9] = *dxbeamM3;    
        v[10] = *dxbeamM4;    
        v[11] = *dxmass;    
        v[12] = *wbeamA4;    
        v[13] = *wbeamA3;    
        v[14] = *wbeamA2;    
        v[15] = *wbeamA1;    
        v[16] = *wbeamA0;    
        v[17] = *dtqfelt;    
        return v;
    }
    
    vector<double> CORE::vl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> CORE::vnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = *dqfelt;    
        v[1] = *dxbeamK4;    
        v[2] = *dxbeamK3;    
        v[3] = *dxbeamK2;    
        v[4] = *dxbeamK1;    
        v[5] = *dxbeamK0;    
        v[6] = *dxbeamM0;    
        v[7] = *dxbeamM1;    
        v[8] = *dxbeamM2;    
        v[9] = *dxbeamM3;    
        v[10] = *dxbeamM4;    
        v[11] = *dxmass;    
        v[12] = *wbeamA4;    
        v[13] = *wbeamA3;    
        v[14] = *wbeamA2;    
        v[15] = *wbeamA1;    
        v[16] = *wbeamA0;    
        v[17] = *dtqfelt;    
        return v;
    }
    
    // Acessors to Arguments, return Matrix<double, n, m>
    
    Matrix<double, 12, 1> CORE::x() const {    
        Matrix<double, 12, 1> m;    
        m(0, 0) = *qfelt;    
        m(1, 0) = *xbeamK4;    
        m(2, 0) = *xbeamK3;    
        m(3, 0) = *xbeamK2;    
        m(4, 0) = *xbeamK1;    
        m(5, 0) = *xbeamK0;    
        m(6, 0) = *xbeamM0;    
        m(7, 0) = *xbeamM1;    
        m(8, 0) = *xbeamM2;    
        m(9, 0) = *xbeamM3;    
        m(10, 0) = *xbeamM4;    
        m(11, 0) = *xmass;    
        return m;
    }
    Matrix<double, 0, 0> CORE::xl() const {    
        Matrix<double, 0, 0> m;    
        return m;
    }
    Matrix<double, 12, 1> CORE::xnl() const {    
        Matrix<double, 12, 1> m;    
        m(0, 0) = *qfelt;    
        m(1, 0) = *xbeamK4;    
        m(2, 0) = *xbeamK3;    
        m(3, 0) = *xbeamK2;    
        m(4, 0) = *xbeamK1;    
        m(5, 0) = *xbeamK0;    
        m(6, 0) = *xbeamM0;    
        m(7, 0) = *xbeamM1;    
        m(8, 0) = *xbeamM2;    
        m(9, 0) = *xbeamM3;    
        m(10, 0) = *xbeamM4;    
        m(11, 0) = *xmass;    
        return m;
    }
    Matrix<double, 12, 1> CORE::dx() const {    
        Matrix<double, 12, 1> m;    
        m(0, 0) = *dqfelt;    
        m(1, 0) = *dxbeamK4;    
        m(2, 0) = *dxbeamK3;    
        m(3, 0) = *dxbeamK2;    
        m(4, 0) = *dxbeamK1;    
        m(5, 0) = *dxbeamK0;    
        m(6, 0) = *dxbeamM0;    
        m(7, 0) = *dxbeamM1;    
        m(8, 0) = *dxbeamM2;    
        m(9, 0) = *dxbeamM3;    
        m(10, 0) = *dxbeamM4;    
        m(11, 0) = *dxmass;    
        return m;
    }
    Matrix<double, 0, 0> CORE::dxl() const {    
        Matrix<double, 0, 0> m;    
        return m;
    }
    Matrix<double, 12, 1> CORE::dxnl() const {    
        Matrix<double, 12, 1> m;    
        m(0, 0) = *dqfelt;    
        m(1, 0) = *dxbeamK4;    
        m(2, 0) = *dxbeamK3;    
        m(3, 0) = *dxbeamK2;    
        m(4, 0) = *dxbeamK1;    
        m(5, 0) = *dxbeamK0;    
        m(6, 0) = *dxbeamM0;    
        m(7, 0) = *dxbeamM1;    
        m(8, 0) = *dxbeamM2;    
        m(9, 0) = *dxbeamM3;    
        m(10, 0) = *dxbeamM4;    
        m(11, 0) = *dxmass;    
        return m;
    }
    Matrix<double, 6, 1> CORE::w() const {    
        Matrix<double, 6, 1> m;    
        m(0, 0) = *wbeamA4;    
        m(1, 0) = *wbeamA3;    
        m(2, 0) = *wbeamA2;    
        m(3, 0) = *wbeamA1;    
        m(4, 0) = *wbeamA0;    
        m(5, 0) = *dtqfelt;    
        return m;
    }
    Matrix<double, 0, 0> CORE::wl() const {    
        Matrix<double, 0, 0> m;    
        return m;
    }
    Matrix<double, 6, 1> CORE::wnl() const {    
        Matrix<double, 6, 1> m;    
        m(0, 0) = *wbeamA4;    
        m(1, 0) = *wbeamA3;    
        m(2, 0) = *wbeamA2;    
        m(3, 0) = *wbeamA1;    
        m(4, 0) = *wbeamA0;    
        m(5, 0) = *dtqfelt;    
        return m;
    }
    Matrix<double, 1, 1> CORE::u() const {    
        Matrix<double, 1, 1> m;    
        m(0, 0) = *uinput;    
        return m;
    }
    Matrix<double, 0, 0> CORE::p() const {    
        Matrix<double, 0, 0> m;    
        return m;
    }
    Matrix<double, 18, 1> CORE::v() const {    
        Matrix<double, 18, 1> m;    
        m(0, 0) = *dqfelt;    
        m(1, 0) = *dxbeamK4;    
        m(2, 0) = *dxbeamK3;    
        m(3, 0) = *dxbeamK2;    
        m(4, 0) = *dxbeamK1;    
        m(5, 0) = *dxbeamK0;    
        m(6, 0) = *dxbeamM0;    
        m(7, 0) = *dxbeamM1;    
        m(8, 0) = *dxbeamM2;    
        m(9, 0) = *dxbeamM3;    
        m(10, 0) = *dxbeamM4;    
        m(11, 0) = *dxmass;    
        m(12, 0) = *wbeamA4;    
        m(13, 0) = *wbeamA3;    
        m(14, 0) = *wbeamA2;    
        m(15, 0) = *wbeamA1;    
        m(16, 0) = *wbeamA0;    
        m(17, 0) = *dtqfelt;    
        return m;
    }
    Matrix<double, 0, 0> CORE::vl() const {    
        Matrix<double, 0, 0> m;    
        return m;
    }
    Matrix<double, 18, 1> CORE::vnl() const {    
        Matrix<double, 18, 1> m;    
        m(0, 0) = *dqfelt;    
        m(1, 0) = *dxbeamK4;    
        m(2, 0) = *dxbeamK3;    
        m(3, 0) = *dxbeamK2;    
        m(4, 0) = *dxbeamK1;    
        m(5, 0) = *dxbeamK0;    
        m(6, 0) = *dxbeamM0;    
        m(7, 0) = *dxbeamM1;    
        m(8, 0) = *dxbeamM2;    
        m(9, 0) = *dxbeamM3;    
        m(10, 0) = *dxbeamM4;    
        m(11, 0) = *dxmass;    
        m(12, 0) = *wbeamA4;    
        m(13, 0) = *wbeamA3;    
        m(14, 0) = *wbeamA2;    
        m(15, 0) = *wbeamA1;    
        m(16, 0) = *wbeamA0;    
        m(17, 0) = *dtqfelt;    
        return m;
    }
    
    // Mutators for Arguments, type = vector<double>
    
    void CORE::set_x(vector<double> & v) {
        *qfelt = v[0];
        *xbeamK4 = v[1];
        *xbeamK3 = v[2];
        *xbeamK2 = v[3];
        *xbeamK1 = v[4];
        *xbeamK0 = v[5];
        *xbeamM0 = v[6];
        *xbeamM1 = v[7];
        *xbeamM2 = v[8];
        *xbeamM3 = v[9];
        *xbeamM4 = v[10];
        *xmass = v[11];
    }
    void CORE::set_xl(vector<double> & v) {
    }
    void CORE::set_xnl(vector<double> & v) {
        *qfelt = v[0];
        *xbeamK4 = v[1];
        *xbeamK3 = v[2];
        *xbeamK2 = v[3];
        *xbeamK1 = v[4];
        *xbeamK0 = v[5];
        *xbeamM0 = v[6];
        *xbeamM1 = v[7];
        *xbeamM2 = v[8];
        *xbeamM3 = v[9];
        *xbeamM4 = v[10];
        *xmass = v[11];
    }
    void CORE::set_dx(vector<double> & v) {
        *dqfelt = v[0];
        *dxbeamK4 = v[1];
        *dxbeamK3 = v[2];
        *dxbeamK2 = v[3];
        *dxbeamK1 = v[4];
        *dxbeamK0 = v[5];
        *dxbeamM0 = v[6];
        *dxbeamM1 = v[7];
        *dxbeamM2 = v[8];
        *dxbeamM3 = v[9];
        *dxbeamM4 = v[10];
        *dxmass = v[11];
    }
    void CORE::set_dxl(vector<double> & v) {
    }
    void CORE::set_dxnl(vector<double> & v) {
        *dqfelt = v[0];
        *dxbeamK4 = v[1];
        *dxbeamK3 = v[2];
        *dxbeamK2 = v[3];
        *dxbeamK1 = v[4];
        *dxbeamK0 = v[5];
        *dxbeamM0 = v[6];
        *dxbeamM1 = v[7];
        *dxbeamM2 = v[8];
        *dxbeamM3 = v[9];
        *dxbeamM4 = v[10];
        *dxmass = v[11];
    }
    void CORE::set_w(vector<double> & v) {
        *wbeamA4 = v[0];
        *wbeamA3 = v[1];
        *wbeamA2 = v[2];
        *wbeamA1 = v[3];
        *wbeamA0 = v[4];
        *dtqfelt = v[5];
    }
    void CORE::set_wl(vector<double> & v) {
    }
    void CORE::set_wnl(vector<double> & v) {
        *wbeamA4 = v[0];
        *wbeamA3 = v[1];
        *wbeamA2 = v[2];
        *wbeamA1 = v[3];
        *wbeamA0 = v[4];
        *dtqfelt = v[5];
    }
    void CORE::set_u(vector<double> & v) {
        *uinput = v[0];
    }
    void CORE::set_p(vector<double> & v) {
    }
    void CORE::set_v(vector<double> & v) {
        *dqfelt = v[0];
        *dxbeamK4 = v[1];
        *dxbeamK3 = v[2];
        *dxbeamK2 = v[3];
        *dxbeamK1 = v[4];
        *dxbeamK0 = v[5];
        *dxbeamM0 = v[6];
        *dxbeamM1 = v[7];
        *dxbeamM2 = v[8];
        *dxbeamM3 = v[9];
        *dxbeamM4 = v[10];
        *dxmass = v[11];
        *wbeamA4 = v[12];
        *wbeamA3 = v[13];
        *wbeamA2 = v[14];
        *wbeamA1 = v[15];
        *wbeamA0 = v[16];
        *dtqfelt = v[17];
    }
    void CORE::set_vl(vector<double> & v) {
    }
    void CORE::set_vnl(vector<double> & v) {
        *dqfelt = v[0];
        *dxbeamK4 = v[1];
        *dxbeamK3 = v[2];
        *dxbeamK2 = v[3];
        *dxbeamK1 = v[4];
        *dxbeamK0 = v[5];
        *dxbeamM0 = v[6];
        *dxbeamM1 = v[7];
        *dxbeamM2 = v[8];
        *dxbeamM3 = v[9];
        *dxbeamM4 = v[10];
        *dxmass = v[11];
        *wbeamA4 = v[12];
        *wbeamA3 = v[13];
        *wbeamA2 = v[14];
        *wbeamA1 = v[15];
        *wbeamA0 = v[16];
        *dtqfelt = v[17];
    }
    
    // Mutators for Arguments, type = Matrix<double, n, m>
    
    void CORE::set_x(Matrix<double, 12, 1> & m) {
        *qfelt = m(0, 0);
        *xbeamK4 = m(1, 0);
        *xbeamK3 = m(2, 0);
        *xbeamK2 = m(3, 0);
        *xbeamK1 = m(4, 0);
        *xbeamK0 = m(5, 0);
        *xbeamM0 = m(6, 0);
        *xbeamM1 = m(7, 0);
        *xbeamM2 = m(8, 0);
        *xbeamM3 = m(9, 0);
        *xbeamM4 = m(10, 0);
        *xmass = m(11, 0);
    }
    void CORE::set_xl(Matrix<double, 0, 0> & m) {
    }
    void CORE::set_xnl(Matrix<double, 12, 1> & m) {
        *qfelt = m(0, 0);
        *xbeamK4 = m(1, 0);
        *xbeamK3 = m(2, 0);
        *xbeamK2 = m(3, 0);
        *xbeamK1 = m(4, 0);
        *xbeamK0 = m(5, 0);
        *xbeamM0 = m(6, 0);
        *xbeamM1 = m(7, 0);
        *xbeamM2 = m(8, 0);
        *xbeamM3 = m(9, 0);
        *xbeamM4 = m(10, 0);
        *xmass = m(11, 0);
    }
    void CORE::set_dx(Matrix<double, 12, 1> & m) {
        *dqfelt = m(0, 0);
        *dxbeamK4 = m(1, 0);
        *dxbeamK3 = m(2, 0);
        *dxbeamK2 = m(3, 0);
        *dxbeamK1 = m(4, 0);
        *dxbeamK0 = m(5, 0);
        *dxbeamM0 = m(6, 0);
        *dxbeamM1 = m(7, 0);
        *dxbeamM2 = m(8, 0);
        *dxbeamM3 = m(9, 0);
        *dxbeamM4 = m(10, 0);
        *dxmass = m(11, 0);
    }
    void CORE::set_dxl(Matrix<double, 0, 0> & m) {
    }
    void CORE::set_dxnl(Matrix<double, 12, 1> & m) {
        *dqfelt = m(0, 0);
        *dxbeamK4 = m(1, 0);
        *dxbeamK3 = m(2, 0);
        *dxbeamK2 = m(3, 0);
        *dxbeamK1 = m(4, 0);
        *dxbeamK0 = m(5, 0);
        *dxbeamM0 = m(6, 0);
        *dxbeamM1 = m(7, 0);
        *dxbeamM2 = m(8, 0);
        *dxbeamM3 = m(9, 0);
        *dxbeamM4 = m(10, 0);
        *dxmass = m(11, 0);
    }
    void CORE::set_w(Matrix<double, 6, 1> & m) {
        *wbeamA4 = m(0, 0);
        *wbeamA3 = m(1, 0);
        *wbeamA2 = m(2, 0);
        *wbeamA1 = m(3, 0);
        *wbeamA0 = m(4, 0);
        *dtqfelt = m(5, 0);
    }
    void CORE::set_wl(Matrix<double, 0, 0> & m) {
    }
    void CORE::set_wnl(Matrix<double, 6, 1> & m) {
        *wbeamA4 = m(0, 0);
        *wbeamA3 = m(1, 0);
        *wbeamA2 = m(2, 0);
        *wbeamA1 = m(3, 0);
        *wbeamA0 = m(4, 0);
        *dtqfelt = m(5, 0);
    }
    void CORE::set_u(Matrix<double, 1, 1> & m) {
        *uinput = m(0, 0);
    }
    void CORE::set_p(Matrix<double, 0, 0> & m) {
    }
    void CORE::set_v(Matrix<double, 18, 1> & m) {
        *dqfelt = m(0, 0);
        *dxbeamK4 = m(1, 0);
        *dxbeamK3 = m(2, 0);
        *dxbeamK2 = m(3, 0);
        *dxbeamK1 = m(4, 0);
        *dxbeamK0 = m(5, 0);
        *dxbeamM0 = m(6, 0);
        *dxbeamM1 = m(7, 0);
        *dxbeamM2 = m(8, 0);
        *dxbeamM3 = m(9, 0);
        *dxbeamM4 = m(10, 0);
        *dxmass = m(11, 0);
        *wbeamA4 = m(12, 0);
        *wbeamA3 = m(13, 0);
        *wbeamA2 = m(14, 0);
        *wbeamA1 = m(15, 0);
        *wbeamA0 = m(16, 0);
        *dtqfelt = m(17, 0);
    }
    void CORE::set_vl(Matrix<double, 0, 0> & m) {
    }
    void CORE::set_vnl(Matrix<double, 18, 1> & m) {
        *dqfelt = m(0, 0);
        *dxbeamK4 = m(1, 0);
        *dxbeamK3 = m(2, 0);
        *dxbeamK2 = m(3, 0);
        *dxbeamK1 = m(4, 0);
        *dxbeamK0 = m(5, 0);
        *dxbeamM0 = m(6, 0);
        *dxbeamM1 = m(7, 0);
        *dxbeamM2 = m(8, 0);
        *dxbeamM3 = m(9, 0);
        *dxbeamM4 = m(10, 0);
        *dxmass = m(11, 0);
        *wbeamA4 = m(12, 0);
        *wbeamA3 = m(13, 0);
        *wbeamA2 = m(14, 0);
        *wbeamA1 = m(15, 0);
        *wbeamA0 = m(16, 0);
        *dtqfelt = m(17, 0);
    }
    
    // Functions Results Accessors
    
    Matrix<double, 0, 0> CORE::jacFll() const {
        return _jacFll;
    }
    Matrix<double, 18, 0> CORE::jacFnll() const {
        return _jacFnll;
    }
    Matrix<double, 0, 0> CORE::Gl() const {
        return _Gl;
    }
    Matrix<double, 18, 1> CORE::Gnl() const {
        return _Gnl;
    }
    Matrix<double, 0, 18> CORE::jacGlnl() const {
        return _jacGlnl;
    }
    Matrix<double, 18, 18> CORE::jacGnlnl() const {
        return _jacGnlnl;
    }
    Matrix<double, 12, 1> CORE::dxH() const {
        return _dxH;
    }
    Matrix<double, 6, 1> CORE::z() const {
        return _z;
    }
    Matrix<double, 1, 1> CORE::y() const {
        return _y;
    }
    
    // Functions Results Accessors
    
    vector<double> CORE::jacFll_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> CORE::jacFnll_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _jacFnll(0, 0);    
        v[1] = _jacFnll(1, 0);    
        v[2] = _jacFnll(2, 0);    
        v[3] = _jacFnll(3, 0);    
        v[4] = _jacFnll(4, 0);    
        v[5] = _jacFnll(5, 0);    
        v[6] = _jacFnll(6, 0);    
        v[7] = _jacFnll(7, 0);    
        v[8] = _jacFnll(8, 0);    
        v[9] = _jacFnll(9, 0);    
        v[10] = _jacFnll(10, 0);    
        v[11] = _jacFnll(11, 0);    
        v[12] = _jacFnll(12, 0);    
        v[13] = _jacFnll(13, 0);    
        v[14] = _jacFnll(14, 0);    
        v[15] = _jacFnll(15, 0);    
        v[16] = _jacFnll(16, 0);    
        v[17] = _jacFnll(17, 0);    
        return v;
    }
    vector<double> CORE::Gl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> CORE::Gnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _Gnl(0, 0);    
        v[1] = _Gnl(1, 0);    
        v[2] = _Gnl(2, 0);    
        v[3] = _Gnl(3, 0);    
        v[4] = _Gnl(4, 0);    
        v[5] = _Gnl(5, 0);    
        v[6] = _Gnl(6, 0);    
        v[7] = _Gnl(7, 0);    
        v[8] = _Gnl(8, 0);    
        v[9] = _Gnl(9, 0);    
        v[10] = _Gnl(10, 0);    
        v[11] = _Gnl(11, 0);    
        v[12] = _Gnl(12, 0);    
        v[13] = _Gnl(13, 0);    
        v[14] = _Gnl(14, 0);    
        v[15] = _Gnl(15, 0);    
        v[16] = _Gnl(16, 0);    
        v[17] = _Gnl(17, 0);    
        return v;
    }
    vector<double> CORE::jacGlnl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> CORE::jacGnlnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _jacGnlnl(0, 0);    
        v[1] = _jacGnlnl(1, 0);    
        v[2] = _jacGnlnl(2, 0);    
        v[3] = _jacGnlnl(3, 0);    
        v[4] = _jacGnlnl(4, 0);    
        v[5] = _jacGnlnl(5, 0);    
        v[6] = _jacGnlnl(6, 0);    
        v[7] = _jacGnlnl(7, 0);    
        v[8] = _jacGnlnl(8, 0);    
        v[9] = _jacGnlnl(9, 0);    
        v[10] = _jacGnlnl(10, 0);    
        v[11] = _jacGnlnl(11, 0);    
        v[12] = _jacGnlnl(12, 0);    
        v[13] = _jacGnlnl(13, 0);    
        v[14] = _jacGnlnl(14, 0);    
        v[15] = _jacGnlnl(15, 0);    
        v[16] = _jacGnlnl(16, 0);    
        v[17] = _jacGnlnl(17, 0);    
        return v;
    }
    vector<double> CORE::dxH_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = _dxH(0, 0);    
        v[1] = _dxH(1, 0);    
        v[2] = _dxH(2, 0);    
        v[3] = _dxH(3, 0);    
        v[4] = _dxH(4, 0);    
        v[5] = _dxH(5, 0);    
        v[6] = _dxH(6, 0);    
        v[7] = _dxH(7, 0);    
        v[8] = _dxH(8, 0);    
        v[9] = _dxH(9, 0);    
        v[10] = _dxH(10, 0);    
        v[11] = _dxH(11, 0);    
        return v;
    }
    vector<double> CORE::z_vector() const {    
        vector<double> v = vector<double>(6);    
        v[0] = _z(0, 0);    
        v[1] = _z(1, 0);    
        v[2] = _z(2, 0);    
        v[3] = _z(3, 0);    
        v[4] = _z(4, 0);    
        v[5] = _z(5, 0);    
        return v;
    }
    vector<double> CORE::y_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = _y(0, 0);    
        return v;
    }
    
    // Oprations Results Accessors
    
    Matrix<double, 12, 1> CORE::ud_x() const {
        return _ud_x;
    }
    Matrix<double, 0, 0> CORE::ijacFll() const {
        return _ijacFll;
    }
    Matrix<double, 0, 0> CORE::ud_vl() const {
        return _ud_vl;
    }
    Matrix<double, 18, 1> CORE::save_Fnl() const {
        return _save_Fnl;
    }
    double CORE::res_Fnl() const {
        return _res_Fnl;
    }
    Matrix<double, 18, 1> CORE::Fnl() const {
        return _Fnl;
    }
    Matrix<double, 18, 18> CORE::jacFnl() const {
        return _jacFnl;
    }
    Matrix<double, 18, 18> CORE::ijacFnl() const {
        return _ijacFnl;
    }
    Matrix<double, 18, 1> CORE::ud_vnl() const {
        return _ud_vnl;
    }
    double CORE::step_Fnl() const {
        return _step_Fnl;
    }
    
    // Oprations Results Accessors
    
    vector<double> CORE::ud_x_vector() const {    
        vector<double> v = vector<double>(12);    
        v[0] = _ud_x(0, 0);    
        v[1] = _ud_x(1, 0);    
        v[2] = _ud_x(2, 0);    
        v[3] = _ud_x(3, 0);    
        v[4] = _ud_x(4, 0);    
        v[5] = _ud_x(5, 0);    
        v[6] = _ud_x(6, 0);    
        v[7] = _ud_x(7, 0);    
        v[8] = _ud_x(8, 0);    
        v[9] = _ud_x(9, 0);    
        v[10] = _ud_x(10, 0);    
        v[11] = _ud_x(11, 0);    
        return v;
    }
    vector<double> CORE::ijacFll_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> CORE::ud_vl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> CORE::save_Fnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _save_Fnl(0, 0);    
        v[1] = _save_Fnl(1, 0);    
        v[2] = _save_Fnl(2, 0);    
        v[3] = _save_Fnl(3, 0);    
        v[4] = _save_Fnl(4, 0);    
        v[5] = _save_Fnl(5, 0);    
        v[6] = _save_Fnl(6, 0);    
        v[7] = _save_Fnl(7, 0);    
        v[8] = _save_Fnl(8, 0);    
        v[9] = _save_Fnl(9, 0);    
        v[10] = _save_Fnl(10, 0);    
        v[11] = _save_Fnl(11, 0);    
        v[12] = _save_Fnl(12, 0);    
        v[13] = _save_Fnl(13, 0);    
        v[14] = _save_Fnl(14, 0);    
        v[15] = _save_Fnl(15, 0);    
        v[16] = _save_Fnl(16, 0);    
        v[17] = _save_Fnl(17, 0);    
        return v;
    }
    vector<double> CORE::Fnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _Fnl(0, 0);    
        v[1] = _Fnl(1, 0);    
        v[2] = _Fnl(2, 0);    
        v[3] = _Fnl(3, 0);    
        v[4] = _Fnl(4, 0);    
        v[5] = _Fnl(5, 0);    
        v[6] = _Fnl(6, 0);    
        v[7] = _Fnl(7, 0);    
        v[8] = _Fnl(8, 0);    
        v[9] = _Fnl(9, 0);    
        v[10] = _Fnl(10, 0);    
        v[11] = _Fnl(11, 0);    
        v[12] = _Fnl(12, 0);    
        v[13] = _Fnl(13, 0);    
        v[14] = _Fnl(14, 0);    
        v[15] = _Fnl(15, 0);    
        v[16] = _Fnl(16, 0);    
        v[17] = _Fnl(17, 0);    
        return v;
    }
    vector<double> CORE::ud_vnl_vector() const {    
        vector<double> v = vector<double>(18);    
        v[0] = _ud_vnl(0, 0);    
        v[1] = _ud_vnl(1, 0);    
        v[2] = _ud_vnl(2, 0);    
        v[3] = _ud_vnl(3, 0);    
        v[4] = _ud_vnl(4, 0);    
        v[5] = _ud_vnl(5, 0);    
        v[6] = _ud_vnl(6, 0);    
        v[7] = _ud_vnl(7, 0);    
        v[8] = _ud_vnl(8, 0);    
        v[9] = _ud_vnl(9, 0);    
        v[10] = _ud_vnl(10, 0);    
        v[11] = _ud_vnl(11, 0);    
        v[12] = _ud_vnl(12, 0);    
        v[13] = _ud_vnl(13, 0);    
        v[14] = _ud_vnl(14, 0);    
        v[15] = _ud_vnl(15, 0);    
        v[16] = _ud_vnl(16, 0);    
        v[17] = _ud_vnl(17, 0);    
        return v;
    }
    
    // Default Constructor
    
    CORE::CORE(){
        init();
    };
    
    // Constructor with vector state initalization
    
    CORE::CORE(vector<double> & x0){
    
        if (x().size() == x0.size()) {
            set_x(x0);
        }
        else {
            cerr << "Size of x0 does not match size of x" << endl;
            exit(1);
        }
        init();
    };
    
    // Constructor with matrix state initalization
    
    CORE::CORE(Matrix<double, 12, 1> & x0){
    set_x(x0);
        init();
    };
    
    // Default Destructor
    
    CORE::~CORE(){
    };


// PRIVATE    
    
    // Functions Results Updates
    
    void CORE::jacFll_update(){
    };
    void CORE::jacFnll_update(){
    };
    void CORE::Gl_update(){
    };
    void CORE::Gnl_update(){
    _Gnl(0, 0) = -1.0*(-48000.0*(*dqfelt) + 0.00296119092432705*sqrt(2)*(((*dxbeamM0) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM0)
    )
    : (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    ))) + 0.0141665318398378*sqrt(2)*(((*dxbeamM1) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM1)
    )
    : (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    ))) + 0.0290991853897294*sqrt(2)*(((*dxbeamM2) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM2)
    )
    : (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    ))) + 0.0378570546023177*sqrt(2)*(((*dxbeamM3) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM3)
    )
    : (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    ))) + 0.0362426306787347*sqrt(2)*(((*dxbeamM4) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM4)
    )
    : (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    ))) + 1.0*(((*dxmass) < -1.0e-16) ? (
       2.5*(*dxmass) + 5.0*(*xmass)
    )
    : (((*dxmass) < 1.0e-16) ? (
       5.0*(*xmass)
    )
    : (
       2.5*(*dxmass) + 5.0*(*xmass)
    ))));
    _Gnl(1, 0) = -1.0*(-48000.0*(*dxbeamK4) + 1.0*(((*dxbeamM4) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM4)
    )
    : (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    ))));
    _Gnl(2, 0) = -1.0*(-48000.0*(*dxbeamK3) + 1.0*(((*dxbeamM3) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM3)
    )
    : (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    ))));
    _Gnl(3, 0) = -1.0*(-48000.0*(*dxbeamK2) + 1.0*(((*dxbeamM2) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM2)
    )
    : (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    ))));
    _Gnl(4, 0) = -1.0*(-48000.0*(*dxbeamK1) + 1.0*(((*dxbeamM1) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM1)
    )
    : (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    ))));
    _Gnl(5, 0) = -1.0*(-48000.0*(*dxbeamK0) + 1.0*(((*dxbeamM0) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM0)
    )
    : (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    ))));
    _Gnl(6, 0) = 1.0*(0.00296119092432705*sqrt(2)*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxbeamM0) + 0.01*(*wbeamA0) + 1.0*(((*dxbeamK0) < -1.0e-16) ? (
       1453.80882750639*(*dxbeamK0) + 2907.61765501279*(*xbeamK0)
    )
    : (((*dxbeamK0) < 1.0e-16) ? (
       2907.61765501279*(*xbeamK0)
    )
    : (
       1453.80882750639*(*dxbeamK0) + 2907.61765501279*(*xbeamK0)
    ))) + 0.00296119092432705*sqrt(2)*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(7, 0) = 1.0*(0.0141665318398378*sqrt(2)*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxbeamM1) + 0.0177827941003892*(*wbeamA1) + 1.0*(((*dxbeamK1) < -1.0e-16) ? (
       57096.7809405863*(*dxbeamK1) + 114193.561881173*(*xbeamK1)
    )
    : (((*dxbeamK1) < 1.0e-16) ? (
       114193.561881173*(*xbeamK1)
    )
    : (
       57096.7809405863*(*dxbeamK1) + 114193.561881173*(*xbeamK1)
    ))) + 0.0141665318398378*sqrt(2)*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(8, 0) = 1.0*(0.0290991853897294*sqrt(2)*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxbeamM2) + 0.0316227766016838*(*wbeamA2) + 1.0*(((*dxbeamK2) < -1.0e-16) ? (
       447648.079617165*(*dxbeamK2) + 895296.15923433*(*xbeamK2)
    )
    : (((*dxbeamK2) < 1.0e-16) ? (
       895296.15923433*(*xbeamK2)
    )
    : (
       447648.079617165*(*dxbeamK2) + 895296.15923433*(*xbeamK2)
    ))) + 0.0290991853897294*sqrt(2)*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(9, 0) = 1.0*(0.0378570546023177*sqrt(2)*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxbeamM3) + 0.0562341325190349*(*wbeamA3) + 1.0*(((*dxbeamK3) < -1.0e-16) ? (
       1718984.58632429*(*dxbeamK3) + 3437969.17264858*(*xbeamK3)
    )
    : (((*dxbeamK3) < 1.0e-16) ? (
       3437969.17264858*(*xbeamK3)
    )
    : (
       1718984.58632429*(*dxbeamK3) + 3437969.17264858*(*xbeamK3)
    ))) + 0.0378570546023177*sqrt(2)*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(10, 0) = 1.0*(0.0362426306787347*sqrt(2)*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxbeamM4) + 0.1*(*wbeamA4) + 1.0*(((*dxbeamK4) < -1.0e-16) ? (
       4697377.1429396*(*dxbeamK4) + 9394754.28587921*(*xbeamK4)
    )
    : (((*dxbeamK4) < 1.0e-16) ? (
       9394754.28587921*(*xbeamK4)
    )
    : (
       4697377.1429396*(*dxbeamK4) + 9394754.28587921*(*xbeamK4)
    ))) + 0.0362426306787347*sqrt(2)*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(11, 0) = 1.0*(1.0*(*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    )) + 48000.0*(*dxmass) - 1.0*(*uinput) + 1.0*(((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    ))));
    _Gnl(12, 0) = -1.0*(-1.0*(*wbeamA4) + 1.0*(((*dxbeamM4) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM4)
    )
    : (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    ))));
    _Gnl(13, 0) = -1.0*(-1.0*(*wbeamA3) + 1.0*(((*dxbeamM3) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM3)
    )
    : (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    ))));
    _Gnl(14, 0) = -1.0*(-1.0*(*wbeamA2) + 1.0*(((*dxbeamM2) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM2)
    )
    : (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    ))));
    _Gnl(15, 0) = -1.0*(-1.0*(*wbeamA1) + 1.0*(((*dxbeamM1) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM1)
    )
    : (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    ))));
    _Gnl(16, 0) = -1.0*(-1.0*(*wbeamA0) + 1.0*(((*dxbeamM0) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM0)
    )
    : (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    ))));
    _Gnl(17, 0) = -1.0*(-1.0*(*dtqfelt) + 0.00296119092432705*sqrt(2)*(((*dxbeamM0) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM0)
    )
    : (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    ))) + 0.0141665318398378*sqrt(2)*(((*dxbeamM1) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM1)
    )
    : (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    ))) + 0.0290991853897294*sqrt(2)*(((*dxbeamM2) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM2)
    )
    : (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    ))) + 0.0378570546023177*sqrt(2)*(((*dxbeamM3) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM3)
    )
    : (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    ))) + 0.0362426306787347*sqrt(2)*(((*dxbeamM4) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM4)
    )
    : (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    ))) + 1.0*(((*dxmass) < -1.0e-16) ? (
       2.5*(*dxmass) + 5.0*(*xmass)
    )
    : (((*dxmass) < 1.0e-16) ? (
       5.0*(*xmass)
    )
    : (
       2.5*(*dxmass) + 5.0*(*xmass)
    ))));
    };
    void CORE::jacGlnl_update(){
    };
    void CORE::jacGnlnl_update(){
    _jacGnlnl(6, 0) = -1.0*(*beamalpha0)*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(7, 0) = -1.0*(*beamalpha1)*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(8, 0) = -1.0*(*beamalpha2)*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(9, 0) = -1.0*(*beamalpha3)*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(10, 0) = -1.0*(*beamalpha4)*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(11, 0) = 1.0*(((*dqfelt) < -1.0e-16) ? (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       0
    )
    : (
       (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0
       )
       : (
          (*B)*(*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*B)*(*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*L)*((*B) + 1)*((*dqfelt)/(*L) + (*qfelt)/(*L))) + (*K)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/(*dqfelt) + (((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*qfelt)*pow((*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2) - (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          (*K)*(*dqfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1) + (*K)*(*qfelt)*pow((*dqfelt)/(*L) + (*qfelt)/(*L), (*B))/((*B) + 1)
       ))/pow((*dqfelt), 2)
    )));
    _jacGnlnl(10, 1) = 1.0*(((*dxbeamK4) < -1.0e-16) ? (
       0.5*(*beamK4)
    )
    : (((*dxbeamK4) < 1.0e-16) ? (
       0
    )
    : (
       0.5*(*beamK4)
    )));
    _jacGnlnl(9, 2) = 1.0*(((*dxbeamK3) < -1.0e-16) ? (
       0.5*(*beamK3)
    )
    : (((*dxbeamK3) < 1.0e-16) ? (
       0
    )
    : (
       0.5*(*beamK3)
    )));
    _jacGnlnl(8, 3) = 1.0*(((*dxbeamK2) < -1.0e-16) ? (
       0.5*(*beamK2)
    )
    : (((*dxbeamK2) < 1.0e-16) ? (
       0
    )
    : (
       0.5*(*beamK2)
    )));
    _jacGnlnl(7, 4) = 1.0*(((*dxbeamK1) < -1.0e-16) ? (
       0.5*(*beamK1)
    )
    : (((*dxbeamK1) < 1.0e-16) ? (
       0
    )
    : (
       0.5*(*beamK1)
    )));
    _jacGnlnl(6, 5) = 1.0*(((*dxbeamK0) < -1.0e-16) ? (
       0.5*(*beamK0)
    )
    : (((*dxbeamK0) < 1.0e-16) ? (
       0
    )
    : (
       0.5*(*beamK0)
    )));
    _jacGnlnl(0, 6) = 1.0*(*beamalpha0)*(((*dxbeamM0) < -1.0e-16) ? (
       0.5/(*beamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM0)
    )));
    _jacGnlnl(5, 6) = -1.0*(((*dxbeamM0) < -1.0e-16) ? (
       0.5/(*beamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM0)
    )));
    _jacGnlnl(16, 6) = -1.0*(((*dxbeamM0) < -1.0e-16) ? (
       0.5/(*beamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM0)
    )));
    _jacGnlnl(17, 6) = 1.0*(*beamalpha0)*(((*dxbeamM0) < -1.0e-16) ? (
       0.5/(*beamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM0)
    )));
    _jacGnlnl(0, 7) = 1.0*(*beamalpha1)*(((*dxbeamM1) < -1.0e-16) ? (
       0.5/(*beamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM1)
    )));
    _jacGnlnl(4, 7) = -1.0*(((*dxbeamM1) < -1.0e-16) ? (
       0.5/(*beamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM1)
    )));
    _jacGnlnl(15, 7) = -1.0*(((*dxbeamM1) < -1.0e-16) ? (
       0.5/(*beamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM1)
    )));
    _jacGnlnl(17, 7) = 1.0*(*beamalpha1)*(((*dxbeamM1) < -1.0e-16) ? (
       0.5/(*beamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM1)
    )));
    _jacGnlnl(0, 8) = 1.0*(*beamalpha2)*(((*dxbeamM2) < -1.0e-16) ? (
       0.5/(*beamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM2)
    )));
    _jacGnlnl(3, 8) = -1.0*(((*dxbeamM2) < -1.0e-16) ? (
       0.5/(*beamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM2)
    )));
    _jacGnlnl(14, 8) = -1.0*(((*dxbeamM2) < -1.0e-16) ? (
       0.5/(*beamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM2)
    )));
    _jacGnlnl(17, 8) = 1.0*(*beamalpha2)*(((*dxbeamM2) < -1.0e-16) ? (
       0.5/(*beamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM2)
    )));
    _jacGnlnl(0, 9) = 1.0*(*beamalpha3)*(((*dxbeamM3) < -1.0e-16) ? (
       0.5/(*beamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM3)
    )));
    _jacGnlnl(2, 9) = -1.0*(((*dxbeamM3) < -1.0e-16) ? (
       0.5/(*beamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM3)
    )));
    _jacGnlnl(13, 9) = -1.0*(((*dxbeamM3) < -1.0e-16) ? (
       0.5/(*beamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM3)
    )));
    _jacGnlnl(17, 9) = 1.0*(*beamalpha3)*(((*dxbeamM3) < -1.0e-16) ? (
       0.5/(*beamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM3)
    )));
    _jacGnlnl(0, 10) = 1.0*(*beamalpha4)*(((*dxbeamM4) < -1.0e-16) ? (
       0.5/(*beamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM4)
    )));
    _jacGnlnl(1, 10) = -1.0*(((*dxbeamM4) < -1.0e-16) ? (
       0.5/(*beamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM4)
    )));
    _jacGnlnl(12, 10) = -1.0*(((*dxbeamM4) < -1.0e-16) ? (
       0.5/(*beamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM4)
    )));
    _jacGnlnl(17, 10) = 1.0*(*beamalpha4)*(((*dxbeamM4) < -1.0e-16) ? (
       0.5/(*beamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*beamM4)
    )));
    _jacGnlnl(0, 11) = -1.0*(((*dxmass) < -1.0e-16) ? (
       0.5/(*M)
    )
    : (((*dxmass) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*M)
    )));
    _jacGnlnl(17, 11) = -1.0*(((*dxmass) < -1.0e-16) ? (
       0.5/(*M)
    )
    : (((*dxmass) < 1.0e-16) ? (
       0
    )
    : (
       0.5/(*M)
    )));
    _jacGnlnl(6, 17) = -1.0*(*beamalpha0)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    _jacGnlnl(7, 17) = -1.0*(*beamalpha1)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    _jacGnlnl(8, 17) = -1.0*(*beamalpha2)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    _jacGnlnl(9, 17) = -1.0*(*beamalpha3)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    _jacGnlnl(10, 17) = -1.0*(*beamalpha4)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    _jacGnlnl(11, 17) = 1.0*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       (*A)*pow((*L), 2)*pow((*qfelt)/(*L), (*B))/((*B)*(*qfelt))
    ));
    };
    void CORE::dxH_update(){
    _dxH(0, 0) = (((*dqfelt) < -1.0e-16) ? (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )
    : (((*dqfelt) < 1.0e-16) ? (
       (((*qfelt) <= 0.0) ? (
          0
       )
       : (
          18144368465.0606*pow((*qfelt), 2.5)
       ))
    )
    : (
       -(((*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          5184105275.73159*pow((*qfelt), 3.5)
       ))/(*dqfelt) + (((*dqfelt) + (*qfelt) <= 0.0) ? (
          0.0
       )
       : (
          142857.142857143*(*dqfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5) + 142857.142857143*(*qfelt)*pow(66.6666666666667*(*dqfelt) + 66.6666666666667*(*qfelt), 2.5)
       ))/(*dqfelt)
    )));
    _dxH(1, 0) = (((*dxbeamK4) < -1.0e-16) ? (
       4697377.1429396*(*dxbeamK4) + 9394754.28587921*(*xbeamK4)
    )
    : (((*dxbeamK4) < 1.0e-16) ? (
       9394754.28587921*(*xbeamK4)
    )
    : (
       4697377.1429396*(*dxbeamK4) + 9394754.28587921*(*xbeamK4)
    )));
    _dxH(2, 0) = (((*dxbeamK3) < -1.0e-16) ? (
       1718984.58632429*(*dxbeamK3) + 3437969.17264858*(*xbeamK3)
    )
    : (((*dxbeamK3) < 1.0e-16) ? (
       3437969.17264858*(*xbeamK3)
    )
    : (
       1718984.58632429*(*dxbeamK3) + 3437969.17264858*(*xbeamK3)
    )));
    _dxH(3, 0) = (((*dxbeamK2) < -1.0e-16) ? (
       447648.079617165*(*dxbeamK2) + 895296.15923433*(*xbeamK2)
    )
    : (((*dxbeamK2) < 1.0e-16) ? (
       895296.15923433*(*xbeamK2)
    )
    : (
       447648.079617165*(*dxbeamK2) + 895296.15923433*(*xbeamK2)
    )));
    _dxH(4, 0) = (((*dxbeamK1) < -1.0e-16) ? (
       57096.7809405863*(*dxbeamK1) + 114193.561881173*(*xbeamK1)
    )
    : (((*dxbeamK1) < 1.0e-16) ? (
       114193.561881173*(*xbeamK1)
    )
    : (
       57096.7809405863*(*dxbeamK1) + 114193.561881173*(*xbeamK1)
    )));
    _dxH(5, 0) = (((*dxbeamK0) < -1.0e-16) ? (
       1453.80882750639*(*dxbeamK0) + 2907.61765501279*(*xbeamK0)
    )
    : (((*dxbeamK0) < 1.0e-16) ? (
       2907.61765501279*(*xbeamK0)
    )
    : (
       1453.80882750639*(*dxbeamK0) + 2907.61765501279*(*xbeamK0)
    )));
    _dxH(6, 0) = (((*dxbeamM0) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )
    : (((*dxbeamM0) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM0)
    )
    : (
       20.5361216892768*(*dxbeamM0) + 41.0722433785536*(*xbeamM0)
    )));
    _dxH(7, 0) = (((*dxbeamM1) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )
    : (((*dxbeamM1) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM1)
    )
    : (
       20.5361216892768*(*dxbeamM1) + 41.0722433785536*(*xbeamM1)
    )));
    _dxH(8, 0) = (((*dxbeamM2) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )
    : (((*dxbeamM2) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM2)
    )
    : (
       20.5361216892768*(*dxbeamM2) + 41.0722433785536*(*xbeamM2)
    )));
    _dxH(9, 0) = (((*dxbeamM3) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )
    : (((*dxbeamM3) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM3)
    )
    : (
       20.5361216892768*(*dxbeamM3) + 41.0722433785536*(*xbeamM3)
    )));
    _dxH(10, 0) = (((*dxbeamM4) < -1.0e-16) ? (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )
    : (((*dxbeamM4) < 1.0e-16) ? (
       41.0722433785536*(*xbeamM4)
    )
    : (
       20.5361216892768*(*dxbeamM4) + 41.0722433785536*(*xbeamM4)
    )));
    _dxH(11, 0) = (((*dxmass) < -1.0e-16) ? (
       2.5*(*dxmass) + 5.0*(*xmass)
    )
    : (((*dxmass) < 1.0e-16) ? (
       5.0*(*xmass)
    )
    : (
       2.5*(*dxmass) + 5.0*(*xmass)
    )));
    };
    void CORE::z_update(){
    _z(0, 0) = 0.1*(*wbeamA4);
    _z(1, 0) = 0.0562341325190349*(*wbeamA3);
    _z(2, 0) = 0.0316227766016838*(*wbeamA2);
    _z(3, 0) = 0.0177827941003892*(*wbeamA1);
    _z(4, 0) = 0.01*(*wbeamA0);
    _z(5, 0) = (*dtqfelt)*(((*qfelt) <= 0.0) ? (
       0.0
    )
    : (
       326.59863237109*pow((*qfelt), 1.5)
    ));
    };
    void CORE::y_update(){
    _y(0, 0) = -1.0*(((*dxmass) < -1.0e-16) ? (
       2.5*(*dxmass) + 5.0*(*xmass)
    )
    : (((*dxmass) < 1.0e-16) ? (
       5.0*(*xmass)
    )
    : (
       2.5*(*dxmass) + 5.0*(*xmass)
    )));
    };
    
    // Oprations Results Updates
    
    void CORE::ud_x_update(){
        _ud_x = (x()) + (dx());
    };
    void CORE::ijacFll_update(){
        _ijacFll = jacFll();
    };
    void CORE::ud_vl_update(){
        _ud_vl = jacFll();
    };
    void CORE::save_Fnl_update(){
        _save_Fnl = Fnl();
    };
    void CORE::res_Fnl_update(){
        _res_Fnl = sqrt((Fnl()).dot(Fnl()));
    };
    void CORE::Fnl_update(){
        _Fnl = Gnl();
    };
    void CORE::jacFnl_update(){
        _jacFnl = jacGnlnl();
    };
    void CORE::ijacFnl_update(){
        _ijacFnl = (jacFnl()).inverse();
    };
    void CORE::ud_vnl_update(){
        _ud_vnl = (vnl()) + ((-1.0)*((ijacFnl())*(Fnl())));
    };
    void CORE::step_Fnl_update(){
        _step_Fnl = sqrt(((Fnl()) + ((-1.0)*(save_Fnl()))).dot((Fnl()) + ((-1.0)*(save_Fnl()))));
    };
    
    // Initialization
    
    void CORE::init(){
        
        
        // Functions Results Initialisation Data
        double jacFll_data[] = {};
        double jacFnll_data[] = {};
        double Gl_data[] = {};
        double Gnl_data[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        double jacGlnl_data[] = {};
        double jacGnlnl_data[] = {48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48000.0000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0*(*beamA4), 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0*(*beamA3), 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0*(*beamA2), 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0*(*beamA1), 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1.0*(*beamA0), 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
        double dxH_data[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        double z_data[] = {0, 0, 0, 0, 0, 0};
        double y_data[] = {0};
        
        // Oprations Results Initialisation Data
        double ud_x_data[] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
        double ijacFll_data[] = {};
        double ud_vl_data[] = {};
        double save_Fnl_data[] = {-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0};
        double res_Fnl_data = 0.;
        double Fnl_data[] = {-0.0, -0.0, -0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0};
        double jacFnl_data[] = {48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -0.0, -0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, -0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.056234132519, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0316227766017, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0177827941004, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0};
        double ijacFnl_data[] = {2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.08333333333e-06, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.17154442748e-06, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -6.58807845868e-07, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -3.70474877091e-07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.08333333333e-07, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0};
        double ud_vnl_data[] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
        double step_Fnl_data = 0.;    
        
        // Functions Results Initialisation
        
        _jacFll = Map<Matrix<double, 0, 0>> (jacFll_data);
        _jacFnll = Map<Matrix<double, 18, 0>> (jacFnll_data);
        _Gl = Map<Matrix<double, 0, 0>> (Gl_data);
        _Gnl = Map<Matrix<double, 18, 1>> (Gnl_data);
        _jacGlnl = Map<Matrix<double, 0, 18>> (jacGlnl_data);
        _jacGnlnl = Map<Matrix<double, 18, 18>> (jacGnlnl_data);
        _dxH = Map<Matrix<double, 12, 1>> (dxH_data);
        _z = Map<Matrix<double, 6, 1>> (z_data);
        _y = Map<Matrix<double, 1, 1>> (y_data);
        
        // Operations Results Initialisation
        
        _ud_x = Map<Matrix<double, 12, 1>> (ud_x_data);
        _ijacFll = Map<Matrix<double, 0, 0>> (ijacFll_data);
        _ud_vl = Map<Matrix<double, 0, 0>> (ud_vl_data);
        _save_Fnl = Map<Matrix<double, 18, 1>> (save_Fnl_data);
        _res_Fnl = res_Fnl_data;
        _Fnl = Map<Matrix<double, 18, 1>> (Fnl_data);
        _jacFnl = Map<Matrix<double, 18, 18>> (jacFnl_data);
        _ijacFnl = Map<Matrix<double, 18, 18>> (ijacFnl_data);
        _ud_vnl = Map<Matrix<double, 18, 1>> (ud_vnl_data);
        _step_Fnl = step_Fnl_data;
    };