/*
    Copyright or (c) or Copr. Project-Team S3 (Sound Signals and Systems) and
    Analysis/Synthesis team, Laboratory of Sciences and Technologies of Music and
    Sound (UMR 9912), IRCAM-CNRS-UPMC, 1 place Igor Stravinsky, F-75004 Paris
    * contributors : Antoine Falaize, Thomas Helie,
    * corresponding contributor: antoine.falaize@ircam.fr
    * date: 2016/12/31 12:47:34

    This has been geerated by PyPHS which purpose is to generate C++
    code for the simulation of multiphysics system described by graph structures.

    This software is governed by the CeCILL-B license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-B
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights, and the successive licensors  have only  limited liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-B license and that you accept its terms.

    Created on 2016/12/31 12:47:34

    author: Antoine Falaize


===========================================================================

    This file was automatically generated by PyPHS, date 2017/03/21 23:27:01.

    It contains the code for the simulation of system 'PHSCORE'.

===========================================================================
*/

#include "core.h"

// PUBLIC    
    
    void PHSCORE::update(vector<double> & u_vec, vector<double> & p_vec){
    
        set_u(u_vec);
        set_p(p_vec);
        
        ud_x_update();
        set_x(_ud_x);
        jacFll_update();
        jacFnll_update();
        ijacFll_update();
        Gl_update();
        Gnl_update();
        Fnl_update();
        res_Fnl_update();
        
        unsigned int iter_res_Fnl = 0;
        _step_Fnl = 1;
        while ((iter_res_Fnl<100) & (res_Fnl()>2.22044604925e-16) & (step_Fnl()>2.22044604925e-16)){    
            save_Fnl_update();
            jacGlnl_update();
            jacGnlnl_update();
            jacFnl_update();
            ijacFnl_update();
            ud_vnl_update();
            set_vnl(_ud_vnl);
            Gl_update();
            Gnl_update();
            Fnl_update();
            res_Fnl_update();
            step_Fnl_update();iter_res_Fnl += 1;
        }
        
        ud_vl_update();
        set_vl(_ud_vl);
        dxH_update();
        z_update();
        y_update();
    }
    
    // Acessors to Arguments, return vector<double>
    
    
    vector<double> PHSCORE::x_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *xL;    
        v[1] = *xC;    
        return v;
    }
    
    vector<double> PHSCORE::xl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::xnl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *xL;    
        v[1] = *xC;    
        return v;
    }
    
    vector<double> PHSCORE::dx_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        return v;
    }
    
    vector<double> PHSCORE::dxl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::dxnl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        return v;
    }
    
    vector<double> PHSCORE::w_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = *wD_R;    
        v[1] = *wD_gmin;    
        v[2] = *wD;    
        return v;
    }
    
    vector<double> PHSCORE::wl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *wD_R;    
        v[1] = *wD_gmin;    
        return v;
    }
    
    vector<double> PHSCORE::wnl_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = *wD;    
        return v;
    }
    
    vector<double> PHSCORE::u_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = *uin;    
        return v;
    }
    
    vector<double> PHSCORE::p_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::v_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        v[2] = *wD_R;    
        v[3] = *wD_gmin;    
        v[4] = *wD;    
        return v;
    }
    
    vector<double> PHSCORE::vl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *wD_R;    
        v[1] = *wD_gmin;    
        return v;
    }
    
    vector<double> PHSCORE::vnl_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        v[2] = *wD;    
        return v;
    }
    
    // Acessors to Arguments, return Matrix<double, n, m>
    
    Matrix<double, 2, 1> PHSCORE::x() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *xL;    
        m(1, 0) = *xC;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::xl() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::xnl() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *xL;    
        m(1, 0) = *xC;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::dx() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::dxl() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::dxnl() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        return m;
    }
    Matrix<double, 3, 1> PHSCORE::w() const {    
        Matrix<double, 3, 1> m;    
        m(0, 0) = *wD_R;    
        m(1, 0) = *wD_gmin;    
        m(2, 0) = *wD;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::wl() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *wD_R;    
        m(1, 0) = *wD_gmin;    
        return m;
    }
    Matrix<double, 1, 1> PHSCORE::wnl() const {    
        Matrix<double, 1, 1> m;    
        m(0, 0) = *wD;    
        return m;
    }
    Matrix<double, 1, 1> PHSCORE::u() const {    
        Matrix<double, 1, 1> m;    
        m(0, 0) = *uin;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::p() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 5, 1> PHSCORE::v() const {    
        Matrix<double, 5, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        m(2, 0) = *wD_R;    
        m(3, 0) = *wD_gmin;    
        m(4, 0) = *wD;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::vl() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *wD_R;    
        m(1, 0) = *wD_gmin;    
        return m;
    }
    Matrix<double, 3, 1> PHSCORE::vnl() const {    
        Matrix<double, 3, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        m(2, 0) = *wD;    
        return m;
    }
    
    // Mutators for Arguments, type = vector<double>
    
    void PHSCORE::set_x(vector<double> & v) {
        *xL = v[0];
        *xC = v[1];
    }
    void PHSCORE::set_xl(vector<double> & v) {
    }
    void PHSCORE::set_xnl(vector<double> & v) {
        *xL = v[0];
        *xC = v[1];
    }
    void PHSCORE::set_dx(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
    }
    void PHSCORE::set_dxl(vector<double> & v) {
    }
    void PHSCORE::set_dxnl(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
    }
    void PHSCORE::set_w(vector<double> & v) {
        *wD_R = v[0];
        *wD_gmin = v[1];
        *wD = v[2];
    }
    void PHSCORE::set_wl(vector<double> & v) {
        *wD_R = v[0];
        *wD_gmin = v[1];
    }
    void PHSCORE::set_wnl(vector<double> & v) {
        *wD = v[0];
    }
    void PHSCORE::set_u(vector<double> & v) {
        *uin = v[0];
    }
    void PHSCORE::set_p(vector<double> & v) {
    }
    void PHSCORE::set_v(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
        *wD_R = v[2];
        *wD_gmin = v[3];
        *wD = v[4];
    }
    void PHSCORE::set_vl(vector<double> & v) {
        *wD_R = v[0];
        *wD_gmin = v[1];
    }
    void PHSCORE::set_vnl(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
        *wD = v[2];
    }
    
    // Mutators for Arguments, type = Matrix<double, n, m>
    
    void PHSCORE::set_x(Matrix<double, 2, 1> & m) {
        *xL = m(0, 0);
        *xC = m(1, 0);
    }
    void PHSCORE::set_xl(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_xnl(Matrix<double, 2, 1> & m) {
        *xL = m(0, 0);
        *xC = m(1, 0);
    }
    void PHSCORE::set_dx(Matrix<double, 2, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
    }
    void PHSCORE::set_dxl(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_dxnl(Matrix<double, 2, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
    }
    void PHSCORE::set_w(Matrix<double, 3, 1> & m) {
        *wD_R = m(0, 0);
        *wD_gmin = m(1, 0);
        *wD = m(2, 0);
    }
    void PHSCORE::set_wl(Matrix<double, 2, 1> & m) {
        *wD_R = m(0, 0);
        *wD_gmin = m(1, 0);
    }
    void PHSCORE::set_wnl(Matrix<double, 1, 1> & m) {
        *wD = m(0, 0);
    }
    void PHSCORE::set_u(Matrix<double, 1, 1> & m) {
        *uin = m(0, 0);
    }
    void PHSCORE::set_p(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_v(Matrix<double, 5, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
        *wD_R = m(2, 0);
        *wD_gmin = m(3, 0);
        *wD = m(4, 0);
    }
    void PHSCORE::set_vl(Matrix<double, 2, 1> & m) {
        *wD_R = m(0, 0);
        *wD_gmin = m(1, 0);
    }
    void PHSCORE::set_vnl(Matrix<double, 3, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
        *wD = m(2, 0);
    }
    
    // Functions Results Accessors
    
    Matrix<double, 2, 2> PHSCORE::jacFll() const {
        return _jacFll;
    }
    Matrix<double, 3, 2> PHSCORE::jacFnll() const {
        return _jacFnll;
    }
    Matrix<double, 2, 1> PHSCORE::Gl() const {
        return _Gl;
    }
    Matrix<double, 3, 1> PHSCORE::Gnl() const {
        return _Gnl;
    }
    Matrix<double, 2, 3> PHSCORE::jacGlnl() const {
        return _jacGlnl;
    }
    Matrix<double, 3, 3> PHSCORE::jacGnlnl() const {
        return _jacGnlnl;
    }
    Matrix<double, 2, 1> PHSCORE::dxH() const {
        return _dxH;
    }
    Matrix<double, 3, 1> PHSCORE::z() const {
        return _z;
    }
    Matrix<double, 1, 1> PHSCORE::y() const {
        return _y;
    }
    
    // Functions Results Accessors
    
    vector<double> PHSCORE::Gl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _Gl(0, 0);    
        v[1] = _Gl(1, 0);    
        return v;
    }
    vector<double> PHSCORE::Gnl_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _Gnl(0, 0);    
        v[1] = _Gnl(1, 0);    
        v[2] = _Gnl(2, 0);    
        return v;
    }
    vector<double> PHSCORE::dxH_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _dxH(0, 0);    
        v[1] = _dxH(1, 0);    
        return v;
    }
    vector<double> PHSCORE::z_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _z(0, 0);    
        v[1] = _z(1, 0);    
        v[2] = _z(2, 0);    
        return v;
    }
    vector<double> PHSCORE::y_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = _y(0, 0);    
        return v;
    }
    
    // Oprations Results Accessors
    
    Matrix<double, 2, 1> PHSCORE::ud_x() const {
        return _ud_x;
    }
    Matrix<double, 2, 2> PHSCORE::ijacFll() const {
        return _ijacFll;
    }
    Matrix<double, 2, 1> PHSCORE::ud_vl() const {
        return _ud_vl;
    }
    Matrix<double, 3, 1> PHSCORE::save_Fnl() const {
        return _save_Fnl;
    }
    Matrix<double, 3, 1> PHSCORE::Fnl() const {
        return _Fnl;
    }
    Matrix<double, 3, 3> PHSCORE::jacFnl() const {
        return _jacFnl;
    }
    Matrix<double, 3, 3> PHSCORE::ijacFnl() const {
        return _ijacFnl;
    }
    double PHSCORE::res_Fnl() const {
        return _res_Fnl;
    }
    double PHSCORE::step_Fnl() const {
        return _step_Fnl;
    }
    Matrix<double, 3, 1> PHSCORE::ud_vnl() const {
        return _ud_vnl;
    }
    
    // Oprations Results Accessors
    
    vector<double> PHSCORE::ud_x_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _ud_x(0, 0);    
        v[1] = _ud_x(1, 0);    
        return v;
    }
    vector<double> PHSCORE::ud_vl_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _ud_vl(0, 0);    
        v[1] = _ud_vl(1, 0);    
        return v;
    }
    vector<double> PHSCORE::save_Fnl_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _save_Fnl(0, 0);    
        v[1] = _save_Fnl(1, 0);    
        v[2] = _save_Fnl(2, 0);    
        return v;
    }
    vector<double> PHSCORE::Fnl_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _Fnl(0, 0);    
        v[1] = _Fnl(1, 0);    
        v[2] = _Fnl(2, 0);    
        return v;
    }
    vector<double> PHSCORE::ud_vnl_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _ud_vnl(0, 0);    
        v[1] = _ud_vnl(1, 0);    
        v[2] = _ud_vnl(2, 0);    
        return v;
    }
    
    // Default Constructor
    
    PHSCORE::PHSCORE(){
        init();
    };
    
    // Constructor with vector state initalization
    
    PHSCORE::PHSCORE(vector<double> & x0){
    
        if (x().size() == x0.size()) {
            set_x(x0);
        }
        else {
            cerr << "Size of x0 does not match size of x" << endl;
            exit(1);
        }
        init();
    };
    
    // Constructor with matrix state initalization
    
    PHSCORE::PHSCORE(Matrix<double, 2, 1> & x0){
    set_x(x0);
        init();
    };
    
    // Default Destructor
    
    PHSCORE::~PHSCORE(){
    };


// PRIVATE    
    
    // Functions Results Updates
    
    void PHSCORE::jacFll_update(){
    };
    void PHSCORE::jacFnll_update(){
    };
    void PHSCORE::Gl_update(){
    _Gl(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       -10.0*(*dxL) - 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       -20.0*(*xL)
    )
    : (
       -10.0*(*dxL) - 20.0*(*xL)
    )));
    _Gl(1, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       -10.0*(*dxL) - 20.0*(*xL) + 0.0442*log(500000000.0*(*wD) + 1.0)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       -20.0*(*xL) + 0.0442*log(500000000.0*(*wD) + 1.0)
    )
    : (
       -10.0*(*dxL) - 20.0*(*xL) + 0.0442*log(500000000.0*(*wD) + 1.0)
    )));
    };
    void PHSCORE::Gnl_update(){
    _Gnl(0, 0) = (((*dxC) < -2.22044604925031e-16) ? (
       250000.0*(*dxC) + 48000.0*(*dxL) + 1.0*(*uin) + 500000.0*(*xC)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       48000.0*(*dxL) + 1.0*(*uin) + 500000.0*(*xC)
    )
    : (
       250000.0*(*dxC) + 48000.0*(*dxL) + 1.0*(*uin) + 500000.0*(*xC)
    )));
    _Gnl(1, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       48000.0*(*dxC) - 10.0*(*dxL) - 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       48000.0*(*dxC) - 20.0*(*xL)
    )
    : (
       48000.0*(*dxC) - 10.0*(*dxL) - 20.0*(*xL)
    )));
    _Gnl(2, 0) = (*wD);
    };
    void PHSCORE::jacGlnl_update(){
    _jacGlnl(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       -0.5/(*L)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       0
    )
    : (
       -0.5/(*L)
    )));
    _jacGlnl(1, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       -0.5/(*L)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       0
    )
    : (
       -0.5/(*L)
    )));
    _jacGlnl(1, 2) = 1.0*(*mu)*(*v0)/((*Is) + (*wD));
    };
    void PHSCORE::jacGnlnl_update(){
    _jacGnlnl(1, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       -0.5/(*L)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       0
    )
    : (
       -0.5/(*L)
    )));
    _jacGnlnl(0, 1) = (((*dxC) < -2.22044604925031e-16) ? (
       0.5/(*C)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       0
    )
    : (
       0.5/(*C)
    )));
    };
    void PHSCORE::dxH_update(){
    _dxH(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       10.0*(*dxL) + 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       20.0*(*xL)
    )
    : (
       10.0*(*dxL) + 20.0*(*xL)
    )));
    _dxH(1, 0) = (((*dxC) < -2.22044604925031e-16) ? (
       250000.0*(*dxC) + 500000.0*(*xC)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       500000.0*(*xC)
    )
    : (
       250000.0*(*dxC) + 500000.0*(*xC)
    )));
    };
    void PHSCORE::z_update(){
    _z(0, 0) = 0.5*(*wD_R);
    _z(1, 0) = 1000000000000.0*(*wD_gmin);
    _z(2, 0) = 0.0442*log(500000000.0*(*wD) + 1.0);
    };
    void PHSCORE::y_update(){
    _y(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       10.0*(*dxL) + 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       20.0*(*xL)
    )
    : (
       10.0*(*dxL) + 20.0*(*xL)
    )));
    };
    
    // Oprations Results Updates
    
    void PHSCORE::ud_x_update(){
        _ud_x = (x()) + (dx());
    };
    void PHSCORE::ijacFll_update(){
        _ijacFll = (jacFll()).inverse();
    };
    void PHSCORE::ud_vl_update(){
        _ud_vl = (ijacFll())*((-1.0)*(Gl()));
    };
    void PHSCORE::save_Fnl_update(){
        _save_Fnl = Fnl();
    };
    void PHSCORE::Fnl_update(){
        _Fnl = (Gnl()) + ((jacFnll())*((ijacFll())*((-1)*(Gl()))));
    };
    void PHSCORE::jacFnl_update(){
        _jacFnl = (jacGnlnl()) + ((jacFnll())*((ijacFll())*((-1)*(jacGlnl()))));
    };
    void PHSCORE::ijacFnl_update(){
        _ijacFnl = (jacFnl()).inverse();
    };
    void PHSCORE::res_Fnl_update(){
        _res_Fnl = sqrt((Fnl()).dot(Fnl()));
    };
    void PHSCORE::step_Fnl_update(){
        _step_Fnl = sqrt(((Fnl()) + ((-1.0)*(save_Fnl()))).dot((Fnl()) + ((-1.0)*(save_Fnl()))));
    };
    void PHSCORE::ud_vnl_update(){
        _ud_vnl = (vnl()) + ((-1.0)*((ijacFnl())*(Fnl())));
    };
    
    // Initialization
    
    void PHSCORE::init(){
        
        
        // Functions Results Initialisation Data
        double jacFll_data[] = {1, 0, 0, 1};
        double jacFnll_data[] = {1.0*(*Rd), 0, 0, 1.0/(*gmin), 0, -1.0/(*gmin)};
        double Gl_data[] = {0, 0};
        double Gnl_data[] = {0, 0, 0};
        double jacGlnl_data[] = {0, 0, 0, 0, 0, 0};
        double jacGnlnl_data[] = {48000.0000000000, 0, 0, 0, 48000.0000000000, 0, 0, 0, 1};
        double dxH_data[] = {0, 0};
        double z_data[] = {0, 0, 0};
        double y_data[] = {0};
        
        // Oprations Results Initialisation Data
        double ud_x_data[] = {0.0, 0.0};
        double ijacFll_data[] = {1.0, 0.0, 0.0, 1.0};
        double ud_vl_data[] = {0.0, 0.0};
        double save_Fnl_data[] = {0.0, 0.0, 0.0};
        double Fnl_data[] = {0.0, 0.0, 0.0};
        double jacFnl_data[] = {48000.0, 0.0, 0.0, 0.0, 48000.0, 0.0, -2.21e+19, 0.0, 2.21e+19};
        double ijacFnl_data[] = {2.08333333333e-05, 0.0, 0.0, 0.0, 2.08333333333e-05, 0.0, 2.08333333333e-05, 0.0, 4.52488687783e-20};
        double res_Fnl_data = 0.;
        double step_Fnl_data = 0.;
        double ud_vnl_data[] = {0.0, 0.0, 0.0};    
        
        // Functions Results Initialisation
        
        _jacFll = Map<Matrix<double, 2, 2>> (jacFll_data);
        _jacFnll = Map<Matrix<double, 3, 2>> (jacFnll_data);
        _Gl = Map<Matrix<double, 2, 1>> (Gl_data);
        _Gnl = Map<Matrix<double, 3, 1>> (Gnl_data);
        _jacGlnl = Map<Matrix<double, 2, 3>> (jacGlnl_data);
        _jacGnlnl = Map<Matrix<double, 3, 3>> (jacGnlnl_data);
        _dxH = Map<Matrix<double, 2, 1>> (dxH_data);
        _z = Map<Matrix<double, 3, 1>> (z_data);
        _y = Map<Matrix<double, 1, 1>> (y_data);
        
        // Operations Results Initialisation
        
        _ud_x = Map<Matrix<double, 2, 1>> (ud_x_data);
        _ijacFll = Map<Matrix<double, 2, 2>> (ijacFll_data);
        _ud_vl = Map<Matrix<double, 2, 1>> (ud_vl_data);
        _save_Fnl = Map<Matrix<double, 3, 1>> (save_Fnl_data);
        _Fnl = Map<Matrix<double, 3, 1>> (Fnl_data);
        _jacFnl = Map<Matrix<double, 3, 3>> (jacFnl_data);
        _ijacFnl = Map<Matrix<double, 3, 3>> (ijacFnl_data);
        _res_Fnl = res_Fnl_data;
        _step_Fnl = step_Fnl_data;
        _ud_vnl = Map<Matrix<double, 3, 1>> (ud_vnl_data);
    };