/*
    Copyright or (c) or Copr. Project-Team S3 (Sound Signals and Systems) and
    Analysis/Synthesis team, Laboratory of Sciences and Technologies of Music and
    Sound (UMR 9912), IRCAM-CNRS-UPMC, 1 place Igor Stravinsky, F-75004 Paris
    * contributors : Antoine Falaize, Thomas Helie,
    * corresponding contributor: antoine.falaize@ircam.fr
    * date: 2016/12/31 12:47:34

    This has been geerated by PyPHS which purpose is to generate C++
    code for the simulation of multiphysics system described by graph structures.

    This software is governed by the CeCILL-B license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-B
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights, and the successive licensors  have only  limited liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-B license and that you accept its terms.

    Created on 2016/12/31 12:47:34

    author: Antoine Falaize


===========================================================================

    This file was automatically generated by PyPHS, date 2017/01/30 20:13:22.

    It contains the code for the simulation of system 'PHSCORE'.

===========================================================================
*/

#include "core.h"

// PUBLIC    
    
    void PHSCORE::update(vector<double> & u_vec, vector<double> & p_vec){
    
        set_u(u_vec);
        set_p(p_vec);
        
        ud_x_update();
        set_x(_ud_x);
        
        Nnlnl_update();
        Nnly_update();
        c_update();
        Inl_update();
        fnl_update();
        impfunc_update();
        res_impfunc_update();
        
        unsigned int iter_res_impfunc = 0;
        _step_impfunc = 1;
        while ((iter_res_impfunc<100) & (res_impfunc()>2.22044604925e-16) & (step_impfunc()>2.22044604925e-16)){    
            save_impfunc_update();
            jac_fnl_update();
            jac_impfunc_update();
            ijac_impfunc_update();
            ud_vnl_update();
            set_vnl(_ud_vnl);
            fnl_update();
            impfunc_update();
            res_impfunc_update();
            step_impfunc_update();iter_res_impfunc += 1;
        }
        
        dxH_update();
        z_update();
        y_update();
    }
    
    // Acessors to Arguments, return vector<double>
    
    
    vector<double> PHSCORE::x_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *xL;    
        v[1] = *xC;    
        return v;
    }
    
    vector<double> PHSCORE::xl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::dx_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        return v;
    }
    
    vector<double> PHSCORE::w_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = *wD;    
        v[1] = *wD_R;    
        v[2] = *wD_gmin;    
        return v;
    }
    
    vector<double> PHSCORE::u_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = *uin;    
        return v;
    }
    
    vector<double> PHSCORE::p_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::vl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    vector<double> PHSCORE::vnl_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = *dxL;    
        v[1] = *dxC;    
        v[2] = *wD;    
        v[3] = *wD_R;    
        v[4] = *wD_gmin;    
        return v;
    }
    
    // Acessors to Arguments, return Matrix<double, n, m>
    
    Matrix<double, 2, 1> PHSCORE::x() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *xL;    
        m(1, 0) = *xC;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::xl() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 2, 1> PHSCORE::dx() const {    
        Matrix<double, 2, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        return m;
    }
    Matrix<double, 3, 1> PHSCORE::w() const {    
        Matrix<double, 3, 1> m;    
        m(0, 0) = *wD;    
        m(1, 0) = *wD_R;    
        m(2, 0) = *wD_gmin;    
        return m;
    }
    Matrix<double, 1, 1> PHSCORE::u() const {    
        Matrix<double, 1, 1> m;    
        m(0, 0) = *uin;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::p() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 0, 1> PHSCORE::vl() const {    
        Matrix<double, 0, 1> m;    
        return m;
    }
    Matrix<double, 5, 1> PHSCORE::vnl() const {    
        Matrix<double, 5, 1> m;    
        m(0, 0) = *dxL;    
        m(1, 0) = *dxC;    
        m(2, 0) = *wD;    
        m(3, 0) = *wD_R;    
        m(4, 0) = *wD_gmin;    
        return m;
    }
    
    // Mutators for Arguments, type = vector<double>
    
    void PHSCORE::set_x(vector<double> & v) {
        *xL = v[0];
        *xC = v[1];
    }
    void PHSCORE::set_xl(vector<double> & v) {
    }
    void PHSCORE::set_dx(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
    }
    void PHSCORE::set_w(vector<double> & v) {
        *wD = v[0];
        *wD_R = v[1];
        *wD_gmin = v[2];
    }
    void PHSCORE::set_u(vector<double> & v) {
        *uin = v[0];
    }
    void PHSCORE::set_p(vector<double> & v) {
    }
    void PHSCORE::set_vl(vector<double> & v) {
    }
    void PHSCORE::set_vnl(vector<double> & v) {
        *dxL = v[0];
        *dxC = v[1];
        *wD = v[2];
        *wD_R = v[3];
        *wD_gmin = v[4];
    }
    
    // Mutators for Arguments, type = Matrix<double, n, m>
    
    void PHSCORE::set_x(Matrix<double, 2, 1> & m) {
        *xL = m(0, 0);
        *xC = m(1, 0);
    }
    void PHSCORE::set_xl(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_dx(Matrix<double, 2, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
    }
    void PHSCORE::set_w(Matrix<double, 3, 1> & m) {
        *wD = m(0, 0);
        *wD_R = m(1, 0);
        *wD_gmin = m(2, 0);
    }
    void PHSCORE::set_u(Matrix<double, 1, 1> & m) {
        *uin = m(0, 0);
    }
    void PHSCORE::set_p(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_vl(Matrix<double, 0, 1> & m) {
    }
    void PHSCORE::set_vnl(Matrix<double, 5, 1> & m) {
        *dxL = m(0, 0);
        *dxC = m(1, 0);
        *wD = m(2, 0);
        *wD_R = m(3, 0);
        *wD_gmin = m(4, 0);
    }
    
    // Functions Results Accessors
    
    Matrix<double, 2, 1> PHSCORE::dxH() const {
        return _dxH;
    }
    Matrix<double, 3, 1> PHSCORE::z() const {
        return _z;
    }
    Matrix<double, 1, 1> PHSCORE::y() const {
        return _y;
    }
    Matrix<double, 5, 1> PHSCORE::fnl() const {
        return _fnl;
    }
    Matrix<double, 5, 5> PHSCORE::jac_fnl() const {
        return _jac_fnl;
    }
    Matrix<double, 5, 5> PHSCORE::Inl() const {
        return _Inl;
    }
    Matrix<double, 0, 0> PHSCORE::iDl() const {
        return _iDl;
    }
    Matrix<double, 0, 0> PHSCORE::barNlxl() const {
        return _barNlxl;
    }
    Matrix<double, 0, 5> PHSCORE::barNlnl() const {
        return _barNlnl;
    }
    Matrix<double, 0, 1> PHSCORE::barNly() const {
        return _barNly;
    }
    Matrix<double, 5, 5> PHSCORE::barNnlnl() const {
        return _barNnlnl;
    }
    Matrix<double, 5, 0> PHSCORE::barNnll() const {
        return _barNnll;
    }
    Matrix<double, 5, 0> PHSCORE::barNnlxl() const {
        return _barNnlxl;
    }
    Matrix<double, 5, 1> PHSCORE::barNnly() const {
        return _barNnly;
    }
    
    // Functions Results Accessors
    
    vector<double> PHSCORE::dxH_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _dxH(0, 0);    
        v[1] = _dxH(1, 0);    
        return v;
    }
    vector<double> PHSCORE::z_vector() const {    
        vector<double> v = vector<double>(3);    
        v[0] = _z(0, 0);    
        v[1] = _z(1, 0);    
        v[2] = _z(2, 0);    
        return v;
    }
    vector<double> PHSCORE::y_vector() const {    
        vector<double> v = vector<double>(1);    
        v[0] = _y(0, 0);    
        return v;
    }
    vector<double> PHSCORE::fnl_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = _fnl(0, 0);    
        v[1] = _fnl(1, 0);    
        v[2] = _fnl(2, 0);    
        v[3] = _fnl(3, 0);    
        v[4] = _fnl(4, 0);    
        return v;
    }
    vector<double> PHSCORE::iDl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> PHSCORE::barNlxl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> PHSCORE::barNlnl_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    vector<double> PHSCORE::barNly_vector() const {    
        vector<double> v = vector<double>(0);    
        return v;
    }
    
    // Oprations Results Accessors
    
    Matrix<double, 2, 1> PHSCORE::ud_x() const {
        return _ud_x;
    }
    Matrix<double, 5, 5> PHSCORE::Nnlnl() const {
        return _Nnlnl;
    }
    Matrix<double, 5, 1> PHSCORE::Nnly() const {
        return _Nnly;
    }
    Matrix<double, 5, 1> PHSCORE::c() const {
        return _c;
    }
    Matrix<double, 5, 1> PHSCORE::impfunc() const {
        return _impfunc;
    }
    Matrix<double, 5, 1> PHSCORE::save_impfunc() const {
        return _save_impfunc;
    }
    Matrix<double, 5, 5> PHSCORE::jac_impfunc() const {
        return _jac_impfunc;
    }
    Matrix<double, 5, 5> PHSCORE::ijac_impfunc() const {
        return _ijac_impfunc;
    }
    double PHSCORE::res_impfunc() const {
        return _res_impfunc;
    }
    double PHSCORE::step_impfunc() const {
        return _step_impfunc;
    }
    Matrix<double, 5, 1> PHSCORE::ud_vnl() const {
        return _ud_vnl;
    }
    
    // Oprations Results Accessors
    
    vector<double> PHSCORE::ud_x_vector() const {    
        vector<double> v = vector<double>(2);    
        v[0] = _ud_x(0, 0);    
        v[1] = _ud_x(1, 0);    
        return v;
    }
    vector<double> PHSCORE::c_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = _c(0, 0);    
        v[1] = _c(1, 0);    
        v[2] = _c(2, 0);    
        v[3] = _c(3, 0);    
        v[4] = _c(4, 0);    
        return v;
    }
    vector<double> PHSCORE::impfunc_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = _impfunc(0, 0);    
        v[1] = _impfunc(1, 0);    
        v[2] = _impfunc(2, 0);    
        v[3] = _impfunc(3, 0);    
        v[4] = _impfunc(4, 0);    
        return v;
    }
    vector<double> PHSCORE::save_impfunc_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = _save_impfunc(0, 0);    
        v[1] = _save_impfunc(1, 0);    
        v[2] = _save_impfunc(2, 0);    
        v[3] = _save_impfunc(3, 0);    
        v[4] = _save_impfunc(4, 0);    
        return v;
    }
    vector<double> PHSCORE::ud_vnl_vector() const {    
        vector<double> v = vector<double>(5);    
        v[0] = _ud_vnl(0, 0);    
        v[1] = _ud_vnl(1, 0);    
        v[2] = _ud_vnl(2, 0);    
        v[3] = _ud_vnl(3, 0);    
        v[4] = _ud_vnl(4, 0);    
        return v;
    }
    
    // Default Constructor
    
    PHSCORE::PHSCORE(){
        init();
    };
    
    // Constructor with vector state initalization
    
    PHSCORE::PHSCORE(vector<double> & x0){
    
        if (x().size() == x0.size()) {
            set_x(x0);
        }
        else {
            cerr << "Size of x0 does not match size of x" << endl;
            exit(1);
        }
        init();
    };
    
    // Constructor with matrix state initalization
    
    PHSCORE::PHSCORE(Matrix<double, 2, 1> & x0){
    set_x(x0);
        init();
    };
    
    // Default Destructor
    
    PHSCORE::~PHSCORE(){
    };


// PRIVATE    
    
    // Functions Results Updates
    
    void PHSCORE::dxH_update(){
    _dxH(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       10.0*(*dxL) + 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       20.0*(*xL)
    )
    : (
       10.0*(*dxL) + 20.0*(*xL)
    )));
    _dxH(1, 0) = (((*dxC) < -2.22044604925031e-16) ? (
       250000.0*(*dxC) + 500000.0*(*xC)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       500000.0*(*xC)
    )
    : (
       250000.0*(*dxC) + 500000.0*(*xC)
    )));
    };
    void PHSCORE::z_update(){
    _z(0, 0) = 0.0442*log(500000000.0*(*wD) + 1);
    _z(1, 0) = 0.5*(*wD_R);
    _z(2, 0) = 1000000000000.0*(*wD_gmin);
    };
    void PHSCORE::y_update(){
    _y(0, 0) = 1.0*(((*dxL) < -2.22044604925031e-16) ? (
       10.0*(*dxL) + 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       20.0*(*xL)
    )
    : (
       10.0*(*dxL) + 20.0*(*xL)
    )));
    };
    void PHSCORE::fnl_update(){
    _fnl(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       10.0*(*dxL) + 20.0*(*xL)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       20.0*(*xL)
    )
    : (
       10.0*(*dxL) + 20.0*(*xL)
    )));
    _fnl(1, 0) = (((*dxC) < -2.22044604925031e-16) ? (
       250000.0*(*dxC) + 500000.0*(*xC)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       500000.0*(*xC)
    )
    : (
       250000.0*(*dxC) + 500000.0*(*xC)
    )));
    _fnl(2, 0) = 0.0442*log(500000000.0*(*wD) + 1);
    _fnl(3, 0) = 0.5*(*wD_R);
    _fnl(4, 0) = 1000000000000.0*(*wD_gmin);
    };
    void PHSCORE::jac_fnl_update(){
    _jac_fnl(0, 0) = (((*dxL) < -2.22044604925031e-16) ? (
       0.5/(*L)
    )
    : (((*dxL) < 2.22044604925031e-16) ? (
       0
    )
    : (
       0.5/(*L)
    )));
    _jac_fnl(1, 1) = (((*dxC) < -2.22044604925031e-16) ? (
       0.5/(*C)
    )
    : (((*dxC) < 2.22044604925031e-16) ? (
       0
    )
    : (
       0.5/(*C)
    )));
    _jac_fnl(2, 2) = (*mu)*(*v0)/((*Is)*(1 + (*wD)/(*Is)));
    };
    void PHSCORE::Inl_update(){
    };
    void PHSCORE::iDl_update(){
    };
    void PHSCORE::barNlxl_update(){
    };
    void PHSCORE::barNlnl_update(){
    };
    void PHSCORE::barNly_update(){
    };
    void PHSCORE::barNnlnl_update(){
    };
    void PHSCORE::barNnll_update(){
    };
    void PHSCORE::barNnlxl_update(){
    };
    void PHSCORE::barNnly_update(){
    };
    
    // Oprations Results Updates
    
    void PHSCORE::ud_x_update(){
        _ud_x = (x()) + (dx());
    };
    void PHSCORE::Nnlnl_update(){
        _Nnlnl = (barNnlnl()) + (0.0);
    };
    void PHSCORE::Nnly_update(){
        _Nnly = (barNnly()) + (0.0);
    };
    void PHSCORE::c_update(){
        _c = (0.0) + ((Nnly())*(u()));
    };
    void PHSCORE::impfunc_update(){
        _impfunc = (((Inl())*(vnl())) + ((-1.0)*((Nnlnl())*(fnl())))) + ((-1.0)*(c()));
    };
    void PHSCORE::save_impfunc_update(){
        _save_impfunc = impfunc();
    };
    void PHSCORE::jac_impfunc_update(){
        _jac_impfunc = (Inl()) + ((-1.0)*((Nnlnl())*(jac_fnl())));
    };
    void PHSCORE::ijac_impfunc_update(){
        _ijac_impfunc = (jac_impfunc()).inverse();
    };
    void PHSCORE::res_impfunc_update(){
        _res_impfunc = sqrt((impfunc()).dot(impfunc()));
    };
    void PHSCORE::step_impfunc_update(){
        _step_impfunc = sqrt(((impfunc()) + ((-1.0)*(save_impfunc()))).dot((impfunc()) + ((-1.0)*(save_impfunc()))));
    };
    void PHSCORE::ud_vnl_update(){
        _ud_vnl = (vnl()) + ((-1.0)*((ijac_impfunc())*(impfunc())));
    };
    
    // Initialization
    
    void PHSCORE::init(){
        
        
        // Functions Results Initialisation Data
        double dxH_data[] = {0, 0};
        double z_data[] = {0, 0, 0};
        double y_data[] = {0};
        double fnl_data[] = {0, 0, 0, 0, 0};
        double jac_fnl_data[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (*Rd), 0, 0, 0, 0, 0, 1.0/(*gmin)};
        double Inl_data[] = {(*_fs), 0, 0, 0, 0, 0, (*_fs), 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1};
        double iDl_data[] = {};
        double barNlxl_data[] = {};
        double barNlnl_data[] = {};
        double barNly_data[] = {};
        double barNnlnl_data[] = {0, 1.00000000000000, 0, 1.00000000000000, 1.00000000000000, -1.00000000000000, 0, 0, 0, 0, 0, 0, 0, 0, -1.00000000000000, -1.00000000000000, 0, 0, 0, 0, -1.00000000000000, 0, 1.00000000000000, 0, 0};
        double barNnll_data[] = {};
        double barNnlxl_data[] = {};
        double barNnly_data[] = {-1.00000000000000, 0, 0, 0, 0};
        
        // Oprations Results Initialisation Data
        double ud_x_data[] = {0.0, 0.0};
        double Nnlnl_data[] = {0.0, 1.0, 0.0, 1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0, 0.0};
        double Nnly_data[] = {-1.0, 0.0, 0.0, 0.0, 0.0};
        double c_data[] = {0.0, 0.0, 0.0, 0.0, 0.0};
        double impfunc_data[] = {0.0, 0.0, 0.0, 0.0, 0.0};
        double save_impfunc_data[] = {0.0, 0.0, 0.0, 0.0, 0.0};
        double jac_impfunc_data[] = {48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 48000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 22100000.0, 0.5, 0.0, 0.0, 1.0, 0.0, 1e+12, 0.0, -1e+12, 0.0, 1.0};
        double ijac_impfunc_data[] = {2.08333333333e-05, 0.0, 0.0, 0.0, -0.0, 0.0, 2.08333333333e-05, 0.0, 0.0, -0.0, 2.08333333333e-05, 0.0, 4.52488687783e-20, 0.0, -1e-12, -1.04166666667e-05, 0.0, 0.0, 1.0, -0.0, -9.42684766214e-13, 0.0, 4.52488687783e-08, 0.0, 4.52488687783e-20};
        double res_impfunc_data = 0.;
        double step_impfunc_data = 0.;
        double ud_vnl_data[] = {0.0, 0.0, 0.0, 0.0, 0.0};    
        
        // Functions Results Initialisation
        
        _dxH = Map<Matrix<double, 2, 1>> (dxH_data);
        _z = Map<Matrix<double, 3, 1>> (z_data);
        _y = Map<Matrix<double, 1, 1>> (y_data);
        _fnl = Map<Matrix<double, 5, 1>> (fnl_data);
        _jac_fnl = Map<Matrix<double, 5, 5>> (jac_fnl_data);
        _Inl = Map<Matrix<double, 5, 5>> (Inl_data);
        _iDl = Map<Matrix<double, 0, 0>> (iDl_data);
        _barNlxl = Map<Matrix<double, 0, 0>> (barNlxl_data);
        _barNlnl = Map<Matrix<double, 0, 5>> (barNlnl_data);
        _barNly = Map<Matrix<double, 0, 1>> (barNly_data);
        _barNnlnl = Map<Matrix<double, 5, 5>> (barNnlnl_data);
        _barNnll = Map<Matrix<double, 5, 0>> (barNnll_data);
        _barNnlxl = Map<Matrix<double, 5, 0>> (barNnlxl_data);
        _barNnly = Map<Matrix<double, 5, 1>> (barNnly_data);
        
        // Operations Results Initialisation
        
        _ud_x = Map<Matrix<double, 2, 1>> (ud_x_data);
        _Nnlnl = Map<Matrix<double, 5, 5>> (Nnlnl_data);
        _Nnly = Map<Matrix<double, 5, 1>> (Nnly_data);
        _c = Map<Matrix<double, 5, 1>> (c_data);
        _impfunc = Map<Matrix<double, 5, 1>> (impfunc_data);
        _save_impfunc = Map<Matrix<double, 5, 1>> (save_impfunc_data);
        _jac_impfunc = Map<Matrix<double, 5, 5>> (jac_impfunc_data);
        _ijac_impfunc = Map<Matrix<double, 5, 5>> (ijac_impfunc_data);
        _res_impfunc = res_impfunc_data;
        _step_impfunc = step_impfunc_data;
        _ud_vnl = Map<Matrix<double, 5, 1>> (ud_vnl_data);
    };